// Code generated by go-swagger; DO NOT EDIT.

package app_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// PutAPIAppVersionsV3Reader is a Reader for the PutAPIAppVersionsV3 structure.
type PutAPIAppVersionsV3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIAppVersionsV3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutAPIAppVersionsV3Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIAppVersionsV3BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutAPIAppVersionsV3Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIAppVersionsV3NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 407:
		result := NewPutAPIAppVersionsV3ProxyAuthenticationRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutAPIAppVersionsV3Conflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutAPIAppVersionsV3InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIAppVersionsV3Created creates a PutAPIAppVersionsV3Created with default headers values
func NewPutAPIAppVersionsV3Created() *PutAPIAppVersionsV3Created {
	return &PutAPIAppVersionsV3Created{}
}

/* PutAPIAppVersionsV3Created describes a response with status code 201, with default header values.

Created
*/
type PutAPIAppVersionsV3Created struct {
	Payload *models.SherlockAppVersionV3
}

func (o *PutAPIAppVersionsV3Created) Error() string {
	return fmt.Sprintf("[PUT /api/app-versions/v3][%d] putApiAppVersionsV3Created  %+v", 201, o.Payload)
}
func (o *PutAPIAppVersionsV3Created) GetPayload() *models.SherlockAppVersionV3 {
	return o.Payload
}

func (o *PutAPIAppVersionsV3Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SherlockAppVersionV3)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIAppVersionsV3BadRequest creates a PutAPIAppVersionsV3BadRequest with default headers values
func NewPutAPIAppVersionsV3BadRequest() *PutAPIAppVersionsV3BadRequest {
	return &PutAPIAppVersionsV3BadRequest{}
}

/* PutAPIAppVersionsV3BadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutAPIAppVersionsV3BadRequest struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PutAPIAppVersionsV3BadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/app-versions/v3][%d] putApiAppVersionsV3BadRequest  %+v", 400, o.Payload)
}
func (o *PutAPIAppVersionsV3BadRequest) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PutAPIAppVersionsV3BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIAppVersionsV3Forbidden creates a PutAPIAppVersionsV3Forbidden with default headers values
func NewPutAPIAppVersionsV3Forbidden() *PutAPIAppVersionsV3Forbidden {
	return &PutAPIAppVersionsV3Forbidden{}
}

/* PutAPIAppVersionsV3Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PutAPIAppVersionsV3Forbidden struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PutAPIAppVersionsV3Forbidden) Error() string {
	return fmt.Sprintf("[PUT /api/app-versions/v3][%d] putApiAppVersionsV3Forbidden  %+v", 403, o.Payload)
}
func (o *PutAPIAppVersionsV3Forbidden) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PutAPIAppVersionsV3Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIAppVersionsV3NotFound creates a PutAPIAppVersionsV3NotFound with default headers values
func NewPutAPIAppVersionsV3NotFound() *PutAPIAppVersionsV3NotFound {
	return &PutAPIAppVersionsV3NotFound{}
}

/* PutAPIAppVersionsV3NotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutAPIAppVersionsV3NotFound struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PutAPIAppVersionsV3NotFound) Error() string {
	return fmt.Sprintf("[PUT /api/app-versions/v3][%d] putApiAppVersionsV3NotFound  %+v", 404, o.Payload)
}
func (o *PutAPIAppVersionsV3NotFound) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PutAPIAppVersionsV3NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIAppVersionsV3ProxyAuthenticationRequired creates a PutAPIAppVersionsV3ProxyAuthenticationRequired with default headers values
func NewPutAPIAppVersionsV3ProxyAuthenticationRequired() *PutAPIAppVersionsV3ProxyAuthenticationRequired {
	return &PutAPIAppVersionsV3ProxyAuthenticationRequired{}
}

/* PutAPIAppVersionsV3ProxyAuthenticationRequired describes a response with status code 407, with default header values.

Proxy Authentication Required
*/
type PutAPIAppVersionsV3ProxyAuthenticationRequired struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PutAPIAppVersionsV3ProxyAuthenticationRequired) Error() string {
	return fmt.Sprintf("[PUT /api/app-versions/v3][%d] putApiAppVersionsV3ProxyAuthenticationRequired  %+v", 407, o.Payload)
}
func (o *PutAPIAppVersionsV3ProxyAuthenticationRequired) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PutAPIAppVersionsV3ProxyAuthenticationRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIAppVersionsV3Conflict creates a PutAPIAppVersionsV3Conflict with default headers values
func NewPutAPIAppVersionsV3Conflict() *PutAPIAppVersionsV3Conflict {
	return &PutAPIAppVersionsV3Conflict{}
}

/* PutAPIAppVersionsV3Conflict describes a response with status code 409, with default header values.

Conflict
*/
type PutAPIAppVersionsV3Conflict struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PutAPIAppVersionsV3Conflict) Error() string {
	return fmt.Sprintf("[PUT /api/app-versions/v3][%d] putApiAppVersionsV3Conflict  %+v", 409, o.Payload)
}
func (o *PutAPIAppVersionsV3Conflict) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PutAPIAppVersionsV3Conflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIAppVersionsV3InternalServerError creates a PutAPIAppVersionsV3InternalServerError with default headers values
func NewPutAPIAppVersionsV3InternalServerError() *PutAPIAppVersionsV3InternalServerError {
	return &PutAPIAppVersionsV3InternalServerError{}
}

/* PutAPIAppVersionsV3InternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutAPIAppVersionsV3InternalServerError struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PutAPIAppVersionsV3InternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api/app-versions/v3][%d] putApiAppVersionsV3InternalServerError  %+v", 500, o.Payload)
}
func (o *PutAPIAppVersionsV3InternalServerError) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PutAPIAppVersionsV3InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
