/* tslint:disable */
/* eslint-disable */
/**
 * Sherlock
 * The Data Science Platform\'s source-of-truth service. Note: this API will try to load and return associations in responses, so clients won\'t need to make as many requests. This behavior isn\'t recursive, though, so associations of associations are *not* fully loaded (even if it might seem that way from looking at the data types).
 *
 * The version of the OpenAPI document: development
 * Contact: dsp-devops@broadinstitute.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2controllersCreatableChart
 */
export interface V2controllersCreatableChart {
    /**
     * 
     * @type {string}
     * @memberof V2controllersCreatableChart
     */
    appImageGitMainBranch?: string;
    /**
     * 
     * @type {string}
     * @memberof V2controllersCreatableChart
     */
    appImageGitRepo?: string;
    /**
     * 
     * @type {string}
     * @memberof V2controllersCreatableChart
     */
    chartRepo?: string;
    /**
     * 
     * @type {number}
     * @memberof V2controllersCreatableChart
     */
    defaultPort?: number;
    /**
     * 
     * @type {string}
     * @memberof V2controllersCreatableChart
     */
    defaultProtocol?: string;
    /**
     * When creating, will default to the name of the chart
     * @type {string}
     * @memberof V2controllersCreatableChart
     */
    defaultSubdomain?: string;
    /**
     * Required when creating
     * @type {string}
     * @memberof V2controllersCreatableChart
     */
    name?: string;
}

/**
 * Check if a given object implements the V2controllersCreatableChart interface.
 */
export function instanceOfV2controllersCreatableChart(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V2controllersCreatableChartFromJSON(json: any): V2controllersCreatableChart {
    return V2controllersCreatableChartFromJSONTyped(json, false);
}

export function V2controllersCreatableChartFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2controllersCreatableChart {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appImageGitMainBranch': !exists(json, 'appImageGitMainBranch') ? undefined : json['appImageGitMainBranch'],
        'appImageGitRepo': !exists(json, 'appImageGitRepo') ? undefined : json['appImageGitRepo'],
        'chartRepo': !exists(json, 'chartRepo') ? undefined : json['chartRepo'],
        'defaultPort': !exists(json, 'defaultPort') ? undefined : json['defaultPort'],
        'defaultProtocol': !exists(json, 'defaultProtocol') ? undefined : json['defaultProtocol'],
        'defaultSubdomain': !exists(json, 'defaultSubdomain') ? undefined : json['defaultSubdomain'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function V2controllersCreatableChartToJSON(value?: V2controllersCreatableChart | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appImageGitMainBranch': value.appImageGitMainBranch,
        'appImageGitRepo': value.appImageGitRepo,
        'chartRepo': value.chartRepo,
        'defaultPort': value.defaultPort,
        'defaultProtocol': value.defaultProtocol,
        'defaultSubdomain': value.defaultSubdomain,
        'name': value.name,
    };
}

