// Code generated by go-swagger; DO NOT EDIT.

package deploy_hooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// NewPostAPIDeployHooksSlackProceduresV3TestSelectorParams creates a new PostAPIDeployHooksSlackProceduresV3TestSelectorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIDeployHooksSlackProceduresV3TestSelectorParams() *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	return &PostAPIDeployHooksSlackProceduresV3TestSelectorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIDeployHooksSlackProceduresV3TestSelectorParamsWithTimeout creates a new PostAPIDeployHooksSlackProceduresV3TestSelectorParams object
// with the ability to set a timeout on a request.
func NewPostAPIDeployHooksSlackProceduresV3TestSelectorParamsWithTimeout(timeout time.Duration) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	return &PostAPIDeployHooksSlackProceduresV3TestSelectorParams{
		timeout: timeout,
	}
}

// NewPostAPIDeployHooksSlackProceduresV3TestSelectorParamsWithContext creates a new PostAPIDeployHooksSlackProceduresV3TestSelectorParams object
// with the ability to set a context for a request.
func NewPostAPIDeployHooksSlackProceduresV3TestSelectorParamsWithContext(ctx context.Context) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	return &PostAPIDeployHooksSlackProceduresV3TestSelectorParams{
		Context: ctx,
	}
}

// NewPostAPIDeployHooksSlackProceduresV3TestSelectorParamsWithHTTPClient creates a new PostAPIDeployHooksSlackProceduresV3TestSelectorParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIDeployHooksSlackProceduresV3TestSelectorParamsWithHTTPClient(client *http.Client) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	return &PostAPIDeployHooksSlackProceduresV3TestSelectorParams{
		HTTPClient: client,
	}
}

/* PostAPIDeployHooksSlackProceduresV3TestSelectorParams contains all the parameters to send to the API endpoint
   for the post API deploy hooks slack procedures v3 test selector operation.

   Typically these are written to a http.Request.
*/
type PostAPIDeployHooksSlackProceduresV3TestSelectorParams struct {

	/* Request.

	   Whether to fully execute the hook (JSON body helps with CSRF protection)
	*/
	Request *models.SherlockSlackDeployHookTestRunRequest

	/* Selector.

	   The ID of the SlackDeployHook to test
	*/
	Selector string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API deploy hooks slack procedures v3 test selector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) WithDefaults() *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API deploy hooks slack procedures v3 test selector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) WithTimeout(timeout time.Duration) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) WithContext(ctx context.Context) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) WithHTTPClient(client *http.Client) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) WithRequest(request *models.SherlockSlackDeployHookTestRunRequest) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) SetRequest(request *models.SherlockSlackDeployHookTestRunRequest) {
	o.Request = request
}

// WithSelector adds the selector to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) WithSelector(selector string) *PostAPIDeployHooksSlackProceduresV3TestSelectorParams {
	o.SetSelector(selector)
	return o
}

// SetSelector adds the selector to the post API deploy hooks slack procedures v3 test selector params
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) SetSelector(selector string) {
	o.Selector = selector
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIDeployHooksSlackProceduresV3TestSelectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param selector
	if err := r.SetPathParam("selector", o.Selector); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
