// Code generated by go-swagger; DO NOT EDIT.

package deploy_hooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// PostAPIDeployHooksSlackV3Reader is a Reader for the PostAPIDeployHooksSlackV3 structure.
type PostAPIDeployHooksSlackV3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIDeployHooksSlackV3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIDeployHooksSlackV3Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIDeployHooksSlackV3BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIDeployHooksSlackV3Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIDeployHooksSlackV3NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 407:
		result := NewPostAPIDeployHooksSlackV3ProxyAuthenticationRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIDeployHooksSlackV3Conflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIDeployHooksSlackV3InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIDeployHooksSlackV3Created creates a PostAPIDeployHooksSlackV3Created with default headers values
func NewPostAPIDeployHooksSlackV3Created() *PostAPIDeployHooksSlackV3Created {
	return &PostAPIDeployHooksSlackV3Created{}
}

/* PostAPIDeployHooksSlackV3Created describes a response with status code 201, with default header values.

Created
*/
type PostAPIDeployHooksSlackV3Created struct {
	Payload *models.SherlockSlackDeployHookV3
}

func (o *PostAPIDeployHooksSlackV3Created) Error() string {
	return fmt.Sprintf("[POST /api/deploy-hooks/slack/v3][%d] postApiDeployHooksSlackV3Created  %+v", 201, o.Payload)
}
func (o *PostAPIDeployHooksSlackV3Created) GetPayload() *models.SherlockSlackDeployHookV3 {
	return o.Payload
}

func (o *PostAPIDeployHooksSlackV3Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SherlockSlackDeployHookV3)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIDeployHooksSlackV3BadRequest creates a PostAPIDeployHooksSlackV3BadRequest with default headers values
func NewPostAPIDeployHooksSlackV3BadRequest() *PostAPIDeployHooksSlackV3BadRequest {
	return &PostAPIDeployHooksSlackV3BadRequest{}
}

/* PostAPIDeployHooksSlackV3BadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAPIDeployHooksSlackV3BadRequest struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIDeployHooksSlackV3BadRequest) Error() string {
	return fmt.Sprintf("[POST /api/deploy-hooks/slack/v3][%d] postApiDeployHooksSlackV3BadRequest  %+v", 400, o.Payload)
}
func (o *PostAPIDeployHooksSlackV3BadRequest) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIDeployHooksSlackV3BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIDeployHooksSlackV3Forbidden creates a PostAPIDeployHooksSlackV3Forbidden with default headers values
func NewPostAPIDeployHooksSlackV3Forbidden() *PostAPIDeployHooksSlackV3Forbidden {
	return &PostAPIDeployHooksSlackV3Forbidden{}
}

/* PostAPIDeployHooksSlackV3Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostAPIDeployHooksSlackV3Forbidden struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIDeployHooksSlackV3Forbidden) Error() string {
	return fmt.Sprintf("[POST /api/deploy-hooks/slack/v3][%d] postApiDeployHooksSlackV3Forbidden  %+v", 403, o.Payload)
}
func (o *PostAPIDeployHooksSlackV3Forbidden) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIDeployHooksSlackV3Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIDeployHooksSlackV3NotFound creates a PostAPIDeployHooksSlackV3NotFound with default headers values
func NewPostAPIDeployHooksSlackV3NotFound() *PostAPIDeployHooksSlackV3NotFound {
	return &PostAPIDeployHooksSlackV3NotFound{}
}

/* PostAPIDeployHooksSlackV3NotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostAPIDeployHooksSlackV3NotFound struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIDeployHooksSlackV3NotFound) Error() string {
	return fmt.Sprintf("[POST /api/deploy-hooks/slack/v3][%d] postApiDeployHooksSlackV3NotFound  %+v", 404, o.Payload)
}
func (o *PostAPIDeployHooksSlackV3NotFound) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIDeployHooksSlackV3NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIDeployHooksSlackV3ProxyAuthenticationRequired creates a PostAPIDeployHooksSlackV3ProxyAuthenticationRequired with default headers values
func NewPostAPIDeployHooksSlackV3ProxyAuthenticationRequired() *PostAPIDeployHooksSlackV3ProxyAuthenticationRequired {
	return &PostAPIDeployHooksSlackV3ProxyAuthenticationRequired{}
}

/* PostAPIDeployHooksSlackV3ProxyAuthenticationRequired describes a response with status code 407, with default header values.

Proxy Authentication Required
*/
type PostAPIDeployHooksSlackV3ProxyAuthenticationRequired struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIDeployHooksSlackV3ProxyAuthenticationRequired) Error() string {
	return fmt.Sprintf("[POST /api/deploy-hooks/slack/v3][%d] postApiDeployHooksSlackV3ProxyAuthenticationRequired  %+v", 407, o.Payload)
}
func (o *PostAPIDeployHooksSlackV3ProxyAuthenticationRequired) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIDeployHooksSlackV3ProxyAuthenticationRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIDeployHooksSlackV3Conflict creates a PostAPIDeployHooksSlackV3Conflict with default headers values
func NewPostAPIDeployHooksSlackV3Conflict() *PostAPIDeployHooksSlackV3Conflict {
	return &PostAPIDeployHooksSlackV3Conflict{}
}

/* PostAPIDeployHooksSlackV3Conflict describes a response with status code 409, with default header values.

Conflict
*/
type PostAPIDeployHooksSlackV3Conflict struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIDeployHooksSlackV3Conflict) Error() string {
	return fmt.Sprintf("[POST /api/deploy-hooks/slack/v3][%d] postApiDeployHooksSlackV3Conflict  %+v", 409, o.Payload)
}
func (o *PostAPIDeployHooksSlackV3Conflict) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIDeployHooksSlackV3Conflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIDeployHooksSlackV3InternalServerError creates a PostAPIDeployHooksSlackV3InternalServerError with default headers values
func NewPostAPIDeployHooksSlackV3InternalServerError() *PostAPIDeployHooksSlackV3InternalServerError {
	return &PostAPIDeployHooksSlackV3InternalServerError{}
}

/* PostAPIDeployHooksSlackV3InternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAPIDeployHooksSlackV3InternalServerError struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIDeployHooksSlackV3InternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/deploy-hooks/slack/v3][%d] postApiDeployHooksSlackV3InternalServerError  %+v", 500, o.Payload)
}
func (o *PostAPIDeployHooksSlackV3InternalServerError) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIDeployHooksSlackV3InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
