coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

github_checks:
  annotations: false

comment:
  layout: "header, diff, reach"
  behavior: default

ignore:
  - "sherlock/docs"
  - "sherlock-go-client"
  - "sherlock-typescript-client"
  - "**/*_mocks"
