---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sherlock
  description: |
    Sherlock stores information about our Kubernetes-based deployments, including Helm Chart versions and application versions. 
    Sherlock doesn't do the deploying itself--it offers an API that other tools can use to understand our infrastructure.
  tags:
    - go
    - sherlock
    - kubernetes
    - dsp-devops
  annotations:
    github.com/project-slug: broadinstitute/sherlock
spec:
  type: service
  lifecycle: production
  owner: dsp-devops
  providesApis:
    - sherlock-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sherlock-api
  description: |
    The API for Sherlock, which stores information about our Kubernetes-based deployments, including Helm Chart versions and application versions. 
    Sherlock doesn't do the deploying itself--it offers an API that other tools can use to understand our infrastructure.
  tags:
    - go
    - sherlock
    - kubernetes
    - dsp-devops
  annotations:
    github.com/project-slug: broadinstitute/sherlock
spec:
  type: openapi
  lifecycle: production
  owner: dsp-devops
  definition:
    $text: ./sherlock/docs/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sherlock-go-client-lib
  description: |
    Sherlock stores information about our Kubernetes-based deployments, including Helm Chart versions and application versions. 
    Sherlock doesn't do the deploying itself--it offers an API that other tools can use to understand our infrastructure.
  tags:
    - go
    - sherlock
    - kubernetes
    - dsp-devops
  annotations:
    github.com/project-slug: broadinstitute/sherlock
spec:
  type: library
  lifecycle: production
  owner: dsp-devops
  subcomponentOf: sherlock
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sherlock-typescript-client-lib
  description: |
    Sherlock stores information about our Kubernetes-based deployments, including Helm Chart versions and application versions. 
    Sherlock doesn't do the deploying itself--it offers an API that other tools can use to understand our infrastructure.
  tags:
    - go
    - sherlock
    - kubernetes
    - dsp-devops
  annotations:
    github.com/project-slug: broadinstitute/sherlock
spec:
  type: library
  lifecycle: production
  owner: dsp-devops
  subcomponentOf: sherlock
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sherlock-cloudsql
  description: |
    GCP cloudsql postgres instances used by sherlock deployments
  tags:
    - go
    - sherlock
    - kubernetes
    - dsp-devops
  annotations:
    github.com/project-slug: broadinstitute/sherlock
spec:
  type: cloudsql-postgres
  lifecycle: production
  owner: dsp-devops
  dependencyOf:
    - sherlock
