// Code generated by go-swagger; DO NOT EDIT.

package chart_releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/clients/go/client/models"
)

// PostAPIV2ChartReleasesReader is a Reader for the PostAPIV2ChartReleases structure.
type PostAPIV2ChartReleasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV2ChartReleasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV2ChartReleasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV2ChartReleasesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV2ChartReleasesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV2ChartReleasesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 407:
		result := NewPostAPIV2ChartReleasesProxyAuthenticationRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV2ChartReleasesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV2ChartReleasesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV2ChartReleasesOK creates a PostAPIV2ChartReleasesOK with default headers values
func NewPostAPIV2ChartReleasesOK() *PostAPIV2ChartReleasesOK {
	return &PostAPIV2ChartReleasesOK{}
}

/* PostAPIV2ChartReleasesOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV2ChartReleasesOK struct {
	Payload *models.V2controllersChartRelease
}

func (o *PostAPIV2ChartReleasesOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/chart-releases][%d] postApiV2ChartReleasesOK  %+v", 200, o.Payload)
}
func (o *PostAPIV2ChartReleasesOK) GetPayload() *models.V2controllersChartRelease {
	return o.Payload
}

func (o *PostAPIV2ChartReleasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V2controllersChartRelease)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV2ChartReleasesBadRequest creates a PostAPIV2ChartReleasesBadRequest with default headers values
func NewPostAPIV2ChartReleasesBadRequest() *PostAPIV2ChartReleasesBadRequest {
	return &PostAPIV2ChartReleasesBadRequest{}
}

/* PostAPIV2ChartReleasesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAPIV2ChartReleasesBadRequest struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIV2ChartReleasesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/chart-releases][%d] postApiV2ChartReleasesBadRequest  %+v", 400, o.Payload)
}
func (o *PostAPIV2ChartReleasesBadRequest) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV2ChartReleasesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV2ChartReleasesForbidden creates a PostAPIV2ChartReleasesForbidden with default headers values
func NewPostAPIV2ChartReleasesForbidden() *PostAPIV2ChartReleasesForbidden {
	return &PostAPIV2ChartReleasesForbidden{}
}

/* PostAPIV2ChartReleasesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostAPIV2ChartReleasesForbidden struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIV2ChartReleasesForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/chart-releases][%d] postApiV2ChartReleasesForbidden  %+v", 403, o.Payload)
}
func (o *PostAPIV2ChartReleasesForbidden) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV2ChartReleasesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV2ChartReleasesNotFound creates a PostAPIV2ChartReleasesNotFound with default headers values
func NewPostAPIV2ChartReleasesNotFound() *PostAPIV2ChartReleasesNotFound {
	return &PostAPIV2ChartReleasesNotFound{}
}

/* PostAPIV2ChartReleasesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostAPIV2ChartReleasesNotFound struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIV2ChartReleasesNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/chart-releases][%d] postApiV2ChartReleasesNotFound  %+v", 404, o.Payload)
}
func (o *PostAPIV2ChartReleasesNotFound) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV2ChartReleasesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV2ChartReleasesProxyAuthenticationRequired creates a PostAPIV2ChartReleasesProxyAuthenticationRequired with default headers values
func NewPostAPIV2ChartReleasesProxyAuthenticationRequired() *PostAPIV2ChartReleasesProxyAuthenticationRequired {
	return &PostAPIV2ChartReleasesProxyAuthenticationRequired{}
}

/* PostAPIV2ChartReleasesProxyAuthenticationRequired describes a response with status code 407, with default header values.

Proxy Authentication Required
*/
type PostAPIV2ChartReleasesProxyAuthenticationRequired struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIV2ChartReleasesProxyAuthenticationRequired) Error() string {
	return fmt.Sprintf("[POST /api/v2/chart-releases][%d] postApiV2ChartReleasesProxyAuthenticationRequired  %+v", 407, o.Payload)
}
func (o *PostAPIV2ChartReleasesProxyAuthenticationRequired) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV2ChartReleasesProxyAuthenticationRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV2ChartReleasesConflict creates a PostAPIV2ChartReleasesConflict with default headers values
func NewPostAPIV2ChartReleasesConflict() *PostAPIV2ChartReleasesConflict {
	return &PostAPIV2ChartReleasesConflict{}
}

/* PostAPIV2ChartReleasesConflict describes a response with status code 409, with default header values.

Conflict
*/
type PostAPIV2ChartReleasesConflict struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIV2ChartReleasesConflict) Error() string {
	return fmt.Sprintf("[POST /api/v2/chart-releases][%d] postApiV2ChartReleasesConflict  %+v", 409, o.Payload)
}
func (o *PostAPIV2ChartReleasesConflict) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV2ChartReleasesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV2ChartReleasesInternalServerError creates a PostAPIV2ChartReleasesInternalServerError with default headers values
func NewPostAPIV2ChartReleasesInternalServerError() *PostAPIV2ChartReleasesInternalServerError {
	return &PostAPIV2ChartReleasesInternalServerError{}
}

/* PostAPIV2ChartReleasesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAPIV2ChartReleasesInternalServerError struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PostAPIV2ChartReleasesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/chart-releases][%d] postApiV2ChartReleasesInternalServerError  %+v", 500, o.Payload)
}
func (o *PostAPIV2ChartReleasesInternalServerError) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV2ChartReleasesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
