// Code generated by go-swagger; DO NOT EDIT.

package ci_runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV2CiRunsSelectorParams creates a new GetAPIV2CiRunsSelectorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2CiRunsSelectorParams() *GetAPIV2CiRunsSelectorParams {
	return &GetAPIV2CiRunsSelectorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2CiRunsSelectorParamsWithTimeout creates a new GetAPIV2CiRunsSelectorParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2CiRunsSelectorParamsWithTimeout(timeout time.Duration) *GetAPIV2CiRunsSelectorParams {
	return &GetAPIV2CiRunsSelectorParams{
		timeout: timeout,
	}
}

// NewGetAPIV2CiRunsSelectorParamsWithContext creates a new GetAPIV2CiRunsSelectorParams object
// with the ability to set a context for a request.
func NewGetAPIV2CiRunsSelectorParamsWithContext(ctx context.Context) *GetAPIV2CiRunsSelectorParams {
	return &GetAPIV2CiRunsSelectorParams{
		Context: ctx,
	}
}

// NewGetAPIV2CiRunsSelectorParamsWithHTTPClient creates a new GetAPIV2CiRunsSelectorParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2CiRunsSelectorParamsWithHTTPClient(client *http.Client) *GetAPIV2CiRunsSelectorParams {
	return &GetAPIV2CiRunsSelectorParams{
		HTTPClient: client,
	}
}

/* GetAPIV2CiRunsSelectorParams contains all the parameters to send to the API endpoint
   for the get API v2 ci runs selector operation.

   Typically these are written to a http.Request.
*/
type GetAPIV2CiRunsSelectorParams struct {

	/* Selector.

	   The CiRun to get's selector: ID, 'github-actions/' + owner + repo + run ID + attempt number, or 'argo-workflows/' + namespace + name
	*/
	Selector string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 ci runs selector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2CiRunsSelectorParams) WithDefaults() *GetAPIV2CiRunsSelectorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 ci runs selector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2CiRunsSelectorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) WithTimeout(timeout time.Duration) *GetAPIV2CiRunsSelectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) WithContext(ctx context.Context) *GetAPIV2CiRunsSelectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) WithHTTPClient(client *http.Client) *GetAPIV2CiRunsSelectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSelector adds the selector to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) WithSelector(selector string) *GetAPIV2CiRunsSelectorParams {
	o.SetSelector(selector)
	return o
}

// SetSelector adds the selector to the get API v2 ci runs selector params
func (o *GetAPIV2CiRunsSelectorParams) SetSelector(selector string) {
	o.Selector = selector
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2CiRunsSelectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param selector
	if err := r.SetPathParam("selector", o.Selector); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
