version: '3'

networks: 
  sherlock-local-dev:
    driver: bridge

services: 
  sherlock:
    build:
      context: ..
      dockerfile: ./sherlock/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SHERLOCK_db_host: postgres
      SHERLOCK_db_password: password
      GOOGLE_APPLICATION_CREDENTIALS: /home/.config/gcloud/application_default_credentials.json
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/home/.config/gcloud/application_default_credentials.json
    depends_on:
      - database
    networks: 
      - sherlock-local-dev

  database:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    expose: 
      - "5432"
    environment:
      POSTGRES_USER: sherlock
      POSTGRES_PASSWORD: password
    restart: on-failure
    networks: 
      - sherlock-local-dev
