version: '3'

networks: 
  sherlock-local-dev:
    driver: bridge

services: 
  sherlock:
    build:
      context: ..
      dockerfile: ./sherlock/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment: 
      SHERLOCK_DB_INIT: "true"
      SHERLOCK_DB_PASSWORD: "password"
      SHERLOCK_DB_HOST: "postgres"
    depends_on:
      - database
    networks: 
      - sherlock-local-dev

  database:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    expose: 
      - "5432"
    environment:
      POSTGRES_USER: sherlock
      POSTGRES_PASSWORD: password
    restart: on-failure
    networks: 
      - sherlock-local-dev
