with-expecter: true
filename: "mock_{{ .InterfaceNameSnake }}_for_test.go"
dir: "{{ .InterfaceDir }}"
mockname: "{{ .Mock }}{{ .InterfaceNameCamel }}"
outpkg: "{{ .PackageName }}"
inpackage: True

packages:
  github.com/broadinstitute/sherlock/sherlock/internal/slack:
    interfaces:
      mockableClient:
