with-expecter: true
filename: "mock_{{ .InterfaceNameSnake }}.go"
dir: "{{ .InterfaceDir }}/{{ .PackageName }}_mocks"
mockname: "Mock{{ .InterfaceNameCamel }}"
outpkg: "{{ .PackageName }}_mocks"

packages:
  github.com/gin-gonic/gin:
    interfaces:
      IRoutes:
        config:
          dir: ./internal/api/gin_mocks
  github.com/broadinstitute/sherlock/sherlock/internal/ci_hooks:
    interfaces:
      mockableDispatcher:
  github.com/broadinstitute/sherlock/sherlock/internal/clients/github:
    interfaces:
      mockableTopLevelClient:
      mockableActionsClient:
      mockableActivityClient:
      mockableAdminClient:
      mockableAppsClient:
      mockableAuthorizationsClient:
      mockableBillingClient:
      mockableChecksClient:
      mockableCodeScanningClient:
      mockableDependabotClient:
      mockableEnterpriseClient:
      mockableGistsClient:
      mockableGitClient:
      mockableGitignoresClient:
      mockableInteractionsClient:
      mockableIssueImportClient:
      mockableIssuesClient:
      mockableLicensesClient:
      mockableMarketplaceClient:
      mockableMigrationsClient:
      mockableOrganizationsClient:
      mockableProjectsClient:
      mockablePullRequestsClient:
      mockableReactionsClient:
      mockableRepositoriesClient:
      mockableSCIMClient:
      mockableSearchClient:
      mockableSecretScanningClient:
      mockableTeamsClient:
      mockableUsersClient:
  github.com/broadinstitute/sherlock/sherlock/internal/clients/slack:
    interfaces:
      mockableClient:
  github.com/broadinstitute/sherlock/sherlock/internal/clients/pact_broker:
    interfaces:
      mockablePactBroker:
  github.com/broadinstitute/sherlock/sherlock/internal/middleware/authentication/gha_oidc:
    interfaces:
      mockableVerifier:
  github.com/broadinstitute/sherlock/sherlock/internal/role_propagation:
    interfaces:
      propagator:
  github.com/broadinstitute/sherlock/sherlock/internal/role_propagation/intermediary_user:
    interfaces:
      Identifier:
      Fields:
  github.com/broadinstitute/sherlock/sherlock/internal/role_propagation/propagation_engines:
    interfaces:
      PropagationEngine:
      ToleratedUserCalculator:
