dir: '{{ .InterfaceDir }}/{{ .SrcPackageName }}_mocks'
structname: Mock{{ .InterfaceName | camelcase }}
pkgname: '{{ .SrcPackageName }}_mocks'
filename: "mock_{{ .InterfaceName | snakecase }}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/broadinstitute/sherlock/sherlock/internal/ci_hooks:
    interfaces:
      mockableDispatcher: {}
  github.com/broadinstitute/sherlock/sherlock/internal/clients/github:
    interfaces:
      mockableActionsClient: {}
      mockableActivityClient: {}
      mockableAdminClient: {}
      mockableAppsClient: {}
      mockableAuthorizationsClient: {}
      mockableBillingClient: {}
      mockableChecksClient: {}
      mockableCodeScanningClient: {}
      mockableDependabotClient: {}
      mockableEnterpriseClient: {}
      mockableGistsClient: {}
      mockableGitClient: {}
      mockableGitignoresClient: {}
      mockableInteractionsClient: {}
      mockableIssueImportClient: {}
      mockableIssuesClient: {}
      mockableLicensesClient: {}
      mockableMarketplaceClient: {}
      mockableMigrationsClient: {}
      mockableOrganizationsClient: {}
      mockableProjectsClient: {}
      mockablePullRequestsClient: {}
      mockableReactionsClient: {}
      mockableRepositoriesClient: {}
      mockableSCIMClient: {}
      mockableSearchClient: {}
      mockableSecretScanningClient: {}
      mockableTeamsClient: {}
      mockableTopLevelClient: {}
      mockableUsersClient: {}
  github.com/broadinstitute/sherlock/sherlock/internal/clients/google_workspace:
    interfaces:
      WorkspaceClient: {}
  github.com/broadinstitute/sherlock/sherlock/internal/clients/pact_broker:
    interfaces:
      mockablePactBroker: {}
  github.com/broadinstitute/sherlock/sherlock/internal/clients/slack:
    interfaces:
      mockableClient: {}
  github.com/broadinstitute/sherlock/sherlock/internal/middleware/authentication/gha_oidc:
    interfaces:
      mockableVerifier: {}
  github.com/broadinstitute/sherlock/sherlock/internal/role_propagation:
    interfaces:
      propagator: {}
  github.com/broadinstitute/sherlock/sherlock/internal/role_propagation/intermediary_user:
    interfaces:
      Fields: {}
      Identifier: {}
      MayBePresentWhileRemovedFields: {}
  github.com/broadinstitute/sherlock/sherlock/internal/role_propagation/propagation_engines:
    interfaces:
      PropagationEngine: {}
      ToleratedUserCalculator: {}
  github.com/gin-gonic/gin:
    interfaces:
      IRoutes:
        config:
          dir: ./internal/api/gin_mocks
