# coding: utf-8

"""
    Sherlock

    The Data Science Platform's source-of-truth service. Note: this API will try to load and return associations in responses, so clients won't need to make as many requests. This behavior isn't recursive, though, so associations of associations are *not* fully loaded (even if it might seem that way from looking at the data types).

    The version of the OpenAPI document: development
    Contact: dsp-devops@broadinstitute.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sherlock_python_client.api.deploy_hooks_api import DeployHooksApi


class TestDeployHooksApi(unittest.TestCase):
    """DeployHooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeployHooksApi()

    def tearDown(self) -> None:
        pass

    def test_api_deploy_hooks_github_actions_procedures_v3_test_selector_post(self) -> None:
        """Test case for api_deploy_hooks_github_actions_procedures_v3_test_selector_post

        Test a GithubActionsDeployHook
        """
        pass

    def test_api_deploy_hooks_github_actions_v3_get(self) -> None:
        """Test case for api_deploy_hooks_github_actions_v3_get

        List GithubActionsDeployHooks matching a filter
        """
        pass

    def test_api_deploy_hooks_github_actions_v3_post(self) -> None:
        """Test case for api_deploy_hooks_github_actions_v3_post

        Create a GithubActionsDeployHook
        """
        pass

    def test_api_deploy_hooks_github_actions_v3_selector_delete(self) -> None:
        """Test case for api_deploy_hooks_github_actions_v3_selector_delete

        Delete an individual GithubActionsDeployHook
        """
        pass

    def test_api_deploy_hooks_github_actions_v3_selector_get(self) -> None:
        """Test case for api_deploy_hooks_github_actions_v3_selector_get

        Get an individual GithubActionsDeployHook
        """
        pass

    def test_api_deploy_hooks_github_actions_v3_selector_patch(self) -> None:
        """Test case for api_deploy_hooks_github_actions_v3_selector_patch

        Edit an individual GithubActionsDeployHook
        """
        pass

    def test_api_deploy_hooks_slack_procedures_v3_test_selector_post(self) -> None:
        """Test case for api_deploy_hooks_slack_procedures_v3_test_selector_post

        Test a SlackDeployHook
        """
        pass

    def test_api_deploy_hooks_slack_v3_get(self) -> None:
        """Test case for api_deploy_hooks_slack_v3_get

        List SlackDeployHooks matching a filter
        """
        pass

    def test_api_deploy_hooks_slack_v3_post(self) -> None:
        """Test case for api_deploy_hooks_slack_v3_post

        Create a SlackDeployHook
        """
        pass

    def test_api_deploy_hooks_slack_v3_selector_delete(self) -> None:
        """Test case for api_deploy_hooks_slack_v3_selector_delete

        Delete an individual SlackDeployHook
        """
        pass

    def test_api_deploy_hooks_slack_v3_selector_get(self) -> None:
        """Test case for api_deploy_hooks_slack_v3_selector_get

        Get an individual SlackDeployHook
        """
        pass

    def test_api_deploy_hooks_slack_v3_selector_patch(self) -> None:
        """Test case for api_deploy_hooks_slack_v3_selector_patch

        Edit an individual SlackDeployHook
        """
        pass


if __name__ == '__main__':
    unittest.main()
