// Code generated by go-swagger; DO NOT EDIT.

package service_alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// PatchAPIServiceAlertsV3SelectorReader is a Reader for the PatchAPIServiceAlertsV3Selector structure.
type PatchAPIServiceAlertsV3SelectorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPIServiceAlertsV3SelectorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPIServiceAlertsV3SelectorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchAPIServiceAlertsV3SelectorBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPatchAPIServiceAlertsV3SelectorForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchAPIServiceAlertsV3SelectorNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 407:
		result := NewPatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPatchAPIServiceAlertsV3SelectorConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchAPIServiceAlertsV3SelectorInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchAPIServiceAlertsV3SelectorOK creates a PatchAPIServiceAlertsV3SelectorOK with default headers values
func NewPatchAPIServiceAlertsV3SelectorOK() *PatchAPIServiceAlertsV3SelectorOK {
	return &PatchAPIServiceAlertsV3SelectorOK{}
}

/* PatchAPIServiceAlertsV3SelectorOK describes a response with status code 200, with default header values.

OK
*/
type PatchAPIServiceAlertsV3SelectorOK struct {
	Payload *models.SherlockServiceAlertV3
}

func (o *PatchAPIServiceAlertsV3SelectorOK) Error() string {
	return fmt.Sprintf("[PATCH /api/service-alerts/v3/{selector}][%d] patchApiServiceAlertsV3SelectorOK  %+v", 200, o.Payload)
}
func (o *PatchAPIServiceAlertsV3SelectorOK) GetPayload() *models.SherlockServiceAlertV3 {
	return o.Payload
}

func (o *PatchAPIServiceAlertsV3SelectorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SherlockServiceAlertV3)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIServiceAlertsV3SelectorBadRequest creates a PatchAPIServiceAlertsV3SelectorBadRequest with default headers values
func NewPatchAPIServiceAlertsV3SelectorBadRequest() *PatchAPIServiceAlertsV3SelectorBadRequest {
	return &PatchAPIServiceAlertsV3SelectorBadRequest{}
}

/* PatchAPIServiceAlertsV3SelectorBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PatchAPIServiceAlertsV3SelectorBadRequest struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIServiceAlertsV3SelectorBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /api/service-alerts/v3/{selector}][%d] patchApiServiceAlertsV3SelectorBadRequest  %+v", 400, o.Payload)
}
func (o *PatchAPIServiceAlertsV3SelectorBadRequest) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIServiceAlertsV3SelectorBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIServiceAlertsV3SelectorForbidden creates a PatchAPIServiceAlertsV3SelectorForbidden with default headers values
func NewPatchAPIServiceAlertsV3SelectorForbidden() *PatchAPIServiceAlertsV3SelectorForbidden {
	return &PatchAPIServiceAlertsV3SelectorForbidden{}
}

/* PatchAPIServiceAlertsV3SelectorForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PatchAPIServiceAlertsV3SelectorForbidden struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIServiceAlertsV3SelectorForbidden) Error() string {
	return fmt.Sprintf("[PATCH /api/service-alerts/v3/{selector}][%d] patchApiServiceAlertsV3SelectorForbidden  %+v", 403, o.Payload)
}
func (o *PatchAPIServiceAlertsV3SelectorForbidden) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIServiceAlertsV3SelectorForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIServiceAlertsV3SelectorNotFound creates a PatchAPIServiceAlertsV3SelectorNotFound with default headers values
func NewPatchAPIServiceAlertsV3SelectorNotFound() *PatchAPIServiceAlertsV3SelectorNotFound {
	return &PatchAPIServiceAlertsV3SelectorNotFound{}
}

/* PatchAPIServiceAlertsV3SelectorNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PatchAPIServiceAlertsV3SelectorNotFound struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIServiceAlertsV3SelectorNotFound) Error() string {
	return fmt.Sprintf("[PATCH /api/service-alerts/v3/{selector}][%d] patchApiServiceAlertsV3SelectorNotFound  %+v", 404, o.Payload)
}
func (o *PatchAPIServiceAlertsV3SelectorNotFound) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIServiceAlertsV3SelectorNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired creates a PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired with default headers values
func NewPatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired() *PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired {
	return &PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired{}
}

/* PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired describes a response with status code 407, with default header values.

Proxy Authentication Required
*/
type PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired) Error() string {
	return fmt.Sprintf("[PATCH /api/service-alerts/v3/{selector}][%d] patchApiServiceAlertsV3SelectorProxyAuthenticationRequired  %+v", 407, o.Payload)
}
func (o *PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIServiceAlertsV3SelectorProxyAuthenticationRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIServiceAlertsV3SelectorConflict creates a PatchAPIServiceAlertsV3SelectorConflict with default headers values
func NewPatchAPIServiceAlertsV3SelectorConflict() *PatchAPIServiceAlertsV3SelectorConflict {
	return &PatchAPIServiceAlertsV3SelectorConflict{}
}

/* PatchAPIServiceAlertsV3SelectorConflict describes a response with status code 409, with default header values.

Conflict
*/
type PatchAPIServiceAlertsV3SelectorConflict struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIServiceAlertsV3SelectorConflict) Error() string {
	return fmt.Sprintf("[PATCH /api/service-alerts/v3/{selector}][%d] patchApiServiceAlertsV3SelectorConflict  %+v", 409, o.Payload)
}
func (o *PatchAPIServiceAlertsV3SelectorConflict) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIServiceAlertsV3SelectorConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIServiceAlertsV3SelectorInternalServerError creates a PatchAPIServiceAlertsV3SelectorInternalServerError with default headers values
func NewPatchAPIServiceAlertsV3SelectorInternalServerError() *PatchAPIServiceAlertsV3SelectorInternalServerError {
	return &PatchAPIServiceAlertsV3SelectorInternalServerError{}
}

/* PatchAPIServiceAlertsV3SelectorInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PatchAPIServiceAlertsV3SelectorInternalServerError struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIServiceAlertsV3SelectorInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /api/service-alerts/v3/{selector}][%d] patchApiServiceAlertsV3SelectorInternalServerError  %+v", 500, o.Payload)
}
func (o *PatchAPIServiceAlertsV3SelectorInternalServerError) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIServiceAlertsV3SelectorInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
