// Code generated by go-swagger; DO NOT EDIT.

package service_alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// NewPatchAPIServiceAlertsV3SelectorParams creates a new PatchAPIServiceAlertsV3SelectorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPIServiceAlertsV3SelectorParams() *PatchAPIServiceAlertsV3SelectorParams {
	return &PatchAPIServiceAlertsV3SelectorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIServiceAlertsV3SelectorParamsWithTimeout creates a new PatchAPIServiceAlertsV3SelectorParams object
// with the ability to set a timeout on a request.
func NewPatchAPIServiceAlertsV3SelectorParamsWithTimeout(timeout time.Duration) *PatchAPIServiceAlertsV3SelectorParams {
	return &PatchAPIServiceAlertsV3SelectorParams{
		timeout: timeout,
	}
}

// NewPatchAPIServiceAlertsV3SelectorParamsWithContext creates a new PatchAPIServiceAlertsV3SelectorParams object
// with the ability to set a context for a request.
func NewPatchAPIServiceAlertsV3SelectorParamsWithContext(ctx context.Context) *PatchAPIServiceAlertsV3SelectorParams {
	return &PatchAPIServiceAlertsV3SelectorParams{
		Context: ctx,
	}
}

// NewPatchAPIServiceAlertsV3SelectorParamsWithHTTPClient creates a new PatchAPIServiceAlertsV3SelectorParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPIServiceAlertsV3SelectorParamsWithHTTPClient(client *http.Client) *PatchAPIServiceAlertsV3SelectorParams {
	return &PatchAPIServiceAlertsV3SelectorParams{
		HTTPClient: client,
	}
}

/* PatchAPIServiceAlertsV3SelectorParams contains all the parameters to send to the API endpoint
   for the patch API service alerts v3 selector operation.

   Typically these are written to a http.Request.
*/
type PatchAPIServiceAlertsV3SelectorParams struct {

	/* Selector.

	   The selector of the ServiceAlert, which is the guid for a given alert
	*/
	Selector string

	/* ServiceAlert.

	   The edits to make to the ServiceAlert
	*/
	ServiceAlert *models.SherlockServiceAlertV3EditableFields

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API service alerts v3 selector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIServiceAlertsV3SelectorParams) WithDefaults() *PatchAPIServiceAlertsV3SelectorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API service alerts v3 selector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIServiceAlertsV3SelectorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) WithTimeout(timeout time.Duration) *PatchAPIServiceAlertsV3SelectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) WithContext(ctx context.Context) *PatchAPIServiceAlertsV3SelectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) WithHTTPClient(client *http.Client) *PatchAPIServiceAlertsV3SelectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSelector adds the selector to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) WithSelector(selector string) *PatchAPIServiceAlertsV3SelectorParams {
	o.SetSelector(selector)
	return o
}

// SetSelector adds the selector to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) SetSelector(selector string) {
	o.Selector = selector
}

// WithServiceAlert adds the serviceAlert to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) WithServiceAlert(serviceAlert *models.SherlockServiceAlertV3EditableFields) *PatchAPIServiceAlertsV3SelectorParams {
	o.SetServiceAlert(serviceAlert)
	return o
}

// SetServiceAlert adds the serviceAlert to the patch API service alerts v3 selector params
func (o *PatchAPIServiceAlertsV3SelectorParams) SetServiceAlert(serviceAlert *models.SherlockServiceAlertV3EditableFields) {
	o.ServiceAlert = serviceAlert
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIServiceAlertsV3SelectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param selector
	if err := r.SetPathParam("selector", o.Selector); err != nil {
		return err
	}
	if o.ServiceAlert != nil {
		if err := r.SetBodyParam(o.ServiceAlert); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
