// Code generated by go-swagger; DO NOT EDIT.

package changesets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// GetAPIV2SelectorsChangesetsSelectorReader is a Reader for the GetAPIV2SelectorsChangesetsSelector structure.
type GetAPIV2SelectorsChangesetsSelectorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2SelectorsChangesetsSelectorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2SelectorsChangesetsSelectorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV2SelectorsChangesetsSelectorBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV2SelectorsChangesetsSelectorForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV2SelectorsChangesetsSelectorNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 407:
		result := NewGetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetAPIV2SelectorsChangesetsSelectorConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV2SelectorsChangesetsSelectorInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV2SelectorsChangesetsSelectorOK creates a GetAPIV2SelectorsChangesetsSelectorOK with default headers values
func NewGetAPIV2SelectorsChangesetsSelectorOK() *GetAPIV2SelectorsChangesetsSelectorOK {
	return &GetAPIV2SelectorsChangesetsSelectorOK{}
}

/* GetAPIV2SelectorsChangesetsSelectorOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV2SelectorsChangesetsSelectorOK struct {
	Payload []string
}

func (o *GetAPIV2SelectorsChangesetsSelectorOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/selectors/changesets/{selector}][%d] getApiV2SelectorsChangesetsSelectorOK  %+v", 200, o.Payload)
}
func (o *GetAPIV2SelectorsChangesetsSelectorOK) GetPayload() []string {
	return o.Payload
}

func (o *GetAPIV2SelectorsChangesetsSelectorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2SelectorsChangesetsSelectorBadRequest creates a GetAPIV2SelectorsChangesetsSelectorBadRequest with default headers values
func NewGetAPIV2SelectorsChangesetsSelectorBadRequest() *GetAPIV2SelectorsChangesetsSelectorBadRequest {
	return &GetAPIV2SelectorsChangesetsSelectorBadRequest{}
}

/* GetAPIV2SelectorsChangesetsSelectorBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV2SelectorsChangesetsSelectorBadRequest struct {
	Payload *models.ErrorsErrorResponse
}

func (o *GetAPIV2SelectorsChangesetsSelectorBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/selectors/changesets/{selector}][%d] getApiV2SelectorsChangesetsSelectorBadRequest  %+v", 400, o.Payload)
}
func (o *GetAPIV2SelectorsChangesetsSelectorBadRequest) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV2SelectorsChangesetsSelectorBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2SelectorsChangesetsSelectorForbidden creates a GetAPIV2SelectorsChangesetsSelectorForbidden with default headers values
func NewGetAPIV2SelectorsChangesetsSelectorForbidden() *GetAPIV2SelectorsChangesetsSelectorForbidden {
	return &GetAPIV2SelectorsChangesetsSelectorForbidden{}
}

/* GetAPIV2SelectorsChangesetsSelectorForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV2SelectorsChangesetsSelectorForbidden struct {
	Payload *models.ErrorsErrorResponse
}

func (o *GetAPIV2SelectorsChangesetsSelectorForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/selectors/changesets/{selector}][%d] getApiV2SelectorsChangesetsSelectorForbidden  %+v", 403, o.Payload)
}
func (o *GetAPIV2SelectorsChangesetsSelectorForbidden) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV2SelectorsChangesetsSelectorForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2SelectorsChangesetsSelectorNotFound creates a GetAPIV2SelectorsChangesetsSelectorNotFound with default headers values
func NewGetAPIV2SelectorsChangesetsSelectorNotFound() *GetAPIV2SelectorsChangesetsSelectorNotFound {
	return &GetAPIV2SelectorsChangesetsSelectorNotFound{}
}

/* GetAPIV2SelectorsChangesetsSelectorNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV2SelectorsChangesetsSelectorNotFound struct {
	Payload *models.ErrorsErrorResponse
}

func (o *GetAPIV2SelectorsChangesetsSelectorNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/selectors/changesets/{selector}][%d] getApiV2SelectorsChangesetsSelectorNotFound  %+v", 404, o.Payload)
}
func (o *GetAPIV2SelectorsChangesetsSelectorNotFound) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV2SelectorsChangesetsSelectorNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired creates a GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired with default headers values
func NewGetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired() *GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired {
	return &GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired{}
}

/* GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired describes a response with status code 407, with default header values.

Proxy Authentication Required
*/
type GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired struct {
	Payload *models.ErrorsErrorResponse
}

func (o *GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired) Error() string {
	return fmt.Sprintf("[GET /api/v2/selectors/changesets/{selector}][%d] getApiV2SelectorsChangesetsSelectorProxyAuthenticationRequired  %+v", 407, o.Payload)
}
func (o *GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV2SelectorsChangesetsSelectorProxyAuthenticationRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2SelectorsChangesetsSelectorConflict creates a GetAPIV2SelectorsChangesetsSelectorConflict with default headers values
func NewGetAPIV2SelectorsChangesetsSelectorConflict() *GetAPIV2SelectorsChangesetsSelectorConflict {
	return &GetAPIV2SelectorsChangesetsSelectorConflict{}
}

/* GetAPIV2SelectorsChangesetsSelectorConflict describes a response with status code 409, with default header values.

Conflict
*/
type GetAPIV2SelectorsChangesetsSelectorConflict struct {
	Payload *models.ErrorsErrorResponse
}

func (o *GetAPIV2SelectorsChangesetsSelectorConflict) Error() string {
	return fmt.Sprintf("[GET /api/v2/selectors/changesets/{selector}][%d] getApiV2SelectorsChangesetsSelectorConflict  %+v", 409, o.Payload)
}
func (o *GetAPIV2SelectorsChangesetsSelectorConflict) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV2SelectorsChangesetsSelectorConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV2SelectorsChangesetsSelectorInternalServerError creates a GetAPIV2SelectorsChangesetsSelectorInternalServerError with default headers values
func NewGetAPIV2SelectorsChangesetsSelectorInternalServerError() *GetAPIV2SelectorsChangesetsSelectorInternalServerError {
	return &GetAPIV2SelectorsChangesetsSelectorInternalServerError{}
}

/* GetAPIV2SelectorsChangesetsSelectorInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAPIV2SelectorsChangesetsSelectorInternalServerError struct {
	Payload *models.ErrorsErrorResponse
}

func (o *GetAPIV2SelectorsChangesetsSelectorInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/selectors/changesets/{selector}][%d] getApiV2SelectorsChangesetsSelectorInternalServerError  %+v", 500, o.Payload)
}
func (o *GetAPIV2SelectorsChangesetsSelectorInternalServerError) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV2SelectorsChangesetsSelectorInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
