// Code generated by go-swagger; DO NOT EDIT.

package changesets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// NewPostAPIChangesetsProceduresV3PlanParams creates a new PostAPIChangesetsProceduresV3PlanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIChangesetsProceduresV3PlanParams() *PostAPIChangesetsProceduresV3PlanParams {
	return &PostAPIChangesetsProceduresV3PlanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIChangesetsProceduresV3PlanParamsWithTimeout creates a new PostAPIChangesetsProceduresV3PlanParams object
// with the ability to set a timeout on a request.
func NewPostAPIChangesetsProceduresV3PlanParamsWithTimeout(timeout time.Duration) *PostAPIChangesetsProceduresV3PlanParams {
	return &PostAPIChangesetsProceduresV3PlanParams{
		timeout: timeout,
	}
}

// NewPostAPIChangesetsProceduresV3PlanParamsWithContext creates a new PostAPIChangesetsProceduresV3PlanParams object
// with the ability to set a context for a request.
func NewPostAPIChangesetsProceduresV3PlanParamsWithContext(ctx context.Context) *PostAPIChangesetsProceduresV3PlanParams {
	return &PostAPIChangesetsProceduresV3PlanParams{
		Context: ctx,
	}
}

// NewPostAPIChangesetsProceduresV3PlanParamsWithHTTPClient creates a new PostAPIChangesetsProceduresV3PlanParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIChangesetsProceduresV3PlanParamsWithHTTPClient(client *http.Client) *PostAPIChangesetsProceduresV3PlanParams {
	return &PostAPIChangesetsProceduresV3PlanParams{
		HTTPClient: client,
	}
}

/* PostAPIChangesetsProceduresV3PlanParams contains all the parameters to send to the API endpoint
   for the post API changesets procedures v3 plan operation.

   Typically these are written to a http.Request.
*/
type PostAPIChangesetsProceduresV3PlanParams struct {

	/* ChangesetPlanRequest.

	   Info on what version changes or refreshes to plan
	*/
	ChangesetPlanRequest *models.SherlockChangesetV3PlanRequest

	/* VerboseOutput.

	   If full information about the changesets should be returned, defaults to true. If false, only the IDs will be returned.
	*/
	VerboseOutput *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API changesets procedures v3 plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIChangesetsProceduresV3PlanParams) WithDefaults() *PostAPIChangesetsProceduresV3PlanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API changesets procedures v3 plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIChangesetsProceduresV3PlanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) WithTimeout(timeout time.Duration) *PostAPIChangesetsProceduresV3PlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) WithContext(ctx context.Context) *PostAPIChangesetsProceduresV3PlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) WithHTTPClient(client *http.Client) *PostAPIChangesetsProceduresV3PlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChangesetPlanRequest adds the changesetPlanRequest to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) WithChangesetPlanRequest(changesetPlanRequest *models.SherlockChangesetV3PlanRequest) *PostAPIChangesetsProceduresV3PlanParams {
	o.SetChangesetPlanRequest(changesetPlanRequest)
	return o
}

// SetChangesetPlanRequest adds the changesetPlanRequest to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) SetChangesetPlanRequest(changesetPlanRequest *models.SherlockChangesetV3PlanRequest) {
	o.ChangesetPlanRequest = changesetPlanRequest
}

// WithVerboseOutput adds the verboseOutput to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) WithVerboseOutput(verboseOutput *bool) *PostAPIChangesetsProceduresV3PlanParams {
	o.SetVerboseOutput(verboseOutput)
	return o
}

// SetVerboseOutput adds the verboseOutput to the post API changesets procedures v3 plan params
func (o *PostAPIChangesetsProceduresV3PlanParams) SetVerboseOutput(verboseOutput *bool) {
	o.VerboseOutput = verboseOutput
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIChangesetsProceduresV3PlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ChangesetPlanRequest != nil {
		if err := r.SetBodyParam(o.ChangesetPlanRequest); err != nil {
			return err
		}
	}

	if o.VerboseOutput != nil {

		// query param verbose-output
		var qrVerboseOutput bool

		if o.VerboseOutput != nil {
			qrVerboseOutput = *o.VerboseOutput
		}
		qVerboseOutput := swag.FormatBool(qrVerboseOutput)
		if qVerboseOutput != "" {

			if err := r.SetQueryParam("verbose-output", qVerboseOutput); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
