// Code generated by go-swagger; DO NOT EDIT.

package git_commits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new git commits API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for git commits API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PutAPIGitCommitsV3(params *PutAPIGitCommitsV3Params, opts ...ClientOption) (*PutAPIGitCommitsV3Created, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PutAPIGitCommitsV3 upserts a git commit

  Upsert a GitCommit.
*/
func (a *Client) PutAPIGitCommitsV3(params *PutAPIGitCommitsV3Params, opts ...ClientOption) (*PutAPIGitCommitsV3Created, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutAPIGitCommitsV3Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIGitCommitsV3",
		Method:             "PUT",
		PathPattern:        "/api/git-commits/v3",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutAPIGitCommitsV3Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutAPIGitCommitsV3Created)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIGitCommitsV3: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
