# mode should either be "release" or "debug".
# - "release" requires running behind IAP and can connect to a Cloud SQL database.
#   It will use real authentication and authorization.
# - "debug" can run locally but will error if connected to a Cloud SQL database.
#   It will use mock authentication and authorization.
mode: debug

log:
  timestamp: true
  caller: false
  level: debug

db:
  host: localhost
  user: sherlock
  name: sherlock
  port: 5432
  ssl: disable
  maxIdleConnections: 50
  maxOpenConnections: 75
  connectionMaxIdleTime: 0s
  connectionMaxLifetime: 0s
  init: true

  livenessPingInterval: 10s

  # retryConnection will repeatedly try to connect to the database to allow it to come online.
  # Helpful to account for delay in either the Cloud SQL proxy (for release mode) or a local Postgres
  # (for debug mode) starting up simultaneously with Sherlock.
  # Sherlock's liveness probe will not activate until this passes.
  retryConnection:
    times: 10
    interval: 1s

  # Configures logging behavior just for the database
  log:
    slowThreshold: 200ms
    ignoreNotFoundWarning: true
    level: warn

  # autoMigrate will have Gorm align the database schema with its understanding of model structs post-init.
  # It should not be enabled in merged code but can be useful for development, to iterate before adding
  # SQL migration files.
  autoMigrateV2: false

auth:
  updateIntervalMinutes: 15
  broadinstitute:
    domain: broadinstitute.org
  firecloud:
    domain: firecloud.org
    groups:
      fcAdmins: fc-admins@firecloud.org
      firecloudProjectOwners: firecloud-project-owners@firecloud.org
  githubActionsOIDC:
    issuer: https://token.actions.githubusercontent.com
    allowedOrganizations:
      - broadinstitute

  # createTestUsersInMiddleware tells debug-mode Sherlock to generate the test users at the middleware level to facilitate testing.
  createTestUsersInMiddleware: false

  # extraPermissions can be used to grant an exact email address access to "suitable" actions inside Sherlock,
  # regardless of that email correlating to a Firecloud account. This functionality should only be used for
  # service accounts, and the justification for this functionality existing is that adding a service account
  # here is better than actually giving the service account any actual permissions inside the Firecloud org.
  extraPermissions:
    #- email: example@dsp-tools-k8s.iam.gserviceaccount.com
    #  suitable: false

metrics:
  v2:
    enable: true
    updateIntervalMinutes: 5

pagerduty:
  enable: false

slack:
  # When slack.enable is true, Sherlock will initiate a
  # websocket connection with Slack upon boot. It will
  # acknowledge all events it receives, even if it isn't
  # configured to act on them (otherwise, Slack will
  # redeliver repeatedly).
  enable: false

  # When slack.enableMocked is true, Sherlock will act as
  # if slack.enable is true when the Slack client is
  # currently mocked. This is set to true in test_config.yaml.
  enableMocked: false

  # slack.debug enables debug logging in the Slack library.
  # Because it doesn't support leveling, the logs appear at
  # the info level.
  debug: false

  appToken: replace me with token starting with "xapp-"
  botToken: replace me with token starting with "xoxb-"

  colors:
    red: "#ef4444" # tailwind's red-500
    green: "#22c55e" # tailwind's green-500

  behaviors:

    # slack.outgoing.deployHooks controls whether Sherlock
    # should act upon Slack-based deploy hooks.
    deployHooks:
      enable: true

    # slack.outgoing.errors controls whether Sherlock should
    # notify a list of channels upon a 500 error.
    errors:
      enable: true
      statusCodes:
        # "Internal Server Error", sometimes used explicitly
        # but mainly Sherlock's default for when it appears
        # that it is to blame instead of the client.
        - 500
        # "Proxy Authentication Required", used if a request
        # seems not to have been processed by IAP. We notify
        # on it because it is highly unexpected and would
        # indicate a misconfiguration.
        - 407
      channels:
        - "#ap-k8s-monitor"

    reactToMentionsWithEmoji:
      enable: true
      emoji: dsp-beehive

pactbroker:
  url: https://pact-broker.dsp-eng-tools.broadinstitute.org
  auth:
    username: replace-username
    password: replace-password
  enable: false

model:
  environments:
    templates:
      # Uses appVersionResolver = "none", chartVersionResolver = "latest", and helmfileRef = "HEAD"
      autoPopulateCharts:
        - name: honeycomb

beehive:
    chartReleaseUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/chart-release/%s
    environmentUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/environment/%s
    pagerdutyIntegrationUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/pagerduty-integration/%s
