# mode should either be "release" or "debug".
# - "release" requires running behind IAP and can connect to a Cloud SQL database.
#   It will use real authentication and authorization.
# - "debug" can run locally but will error if connected to a Cloud SQL database.
#   It will use mock authentication and authorization.
mode: debug

hooks:
  # If Sherlock should act on CiRun state transitions. Hooks are still subject
  # to the third-party-specific flags elsewhere in this file.
  enable: true
  # If true, hooks will be run asynchronously after the initial call into the
  # hooks package.
  asynchronous: true

log:
  # Always true when mode="release"
  timestamp: true
  # Always true when mode="release"
  caller: false
  level: debug

db:
  host: localhost
  user: sherlock
  name: sherlock
  port: 5432
  ssl: disable
  preparedStatementCache: true
  maxIdleConnections: 50
  maxOpenConnections: 75
  connectionMaxIdleTime: 0s
  connectionMaxLifetime: 0s
  init: true

  livenessPingInterval: 10s

  # retryConnection will repeatedly try to connect to the database to allow it to come online.
  # Helpful to account for delay in either the Cloud SQL proxy (for release mode) or a local Postgres
  # (for debug mode) starting up simultaneously with Sherlock.
  # Sherlock's liveness probe will not activate until this passes.
  retryConnection:
    times: 10
    interval: 1s

  # Configures logging behavior just for the database
  log:
    slowThreshold: 200ms
    ignoreNotFoundWarning: true
    level: warn

  # autoMigrate will have Gorm align the database schema with its understanding of model structs post-init.
  # It should not be enabled in merged code but can be useful for development, to iterate before adding
  # SQL migration files.
  autoMigrateV2: false

auth:
  updateIntervalMinutes: 15
  broadinstitute:
    domain: broadinstitute.org
  firecloud:
    domain: firecloud.org
    groups:
      fcAdmins: fc-admins@firecloud.org
      firecloudProjectOwners: firecloud-project-owners@firecloud.org
  githubActionsOIDC:
    issuer: https://token.actions.githubusercontent.com
    allowedOrganizations:
      - broadinstitute

  # createTestUsersInMiddleware tells debug-mode Sherlock to generate the test users at the middleware level to facilitate testing.
  createTestUsersInMiddleware: false

  # extraPermissions can be used to grant an exact email address access to "suitable" actions inside Sherlock,
  # regardless of that email correlating to a Firecloud account. This functionality should only be used for
  # service accounts, and the justification for this functionality existing is that adding a service account
  # here is better than actually giving the service account any actual permissions inside the Firecloud org.
  extraPermissions:
    #- email: example@dsp-tools-k8s.iam.gserviceaccount.com
    #  suitable: false

metrics:
  v2:
    enable: true
    updateIntervalMinutes: 5

pagerduty:
  enable: false

github:
  # When github.enable is true, requests to GitHub will be
  # made based on the individual behavior flags below.
  enable: false
  # When github.enableMocked is true, Sherlock will act as
  # if github.enable is true when the GitHub client is
  # currently mocked. This is set to true in test_config.yaml.
  enableMocked: false

  token: replace me with token starting with "ghp_"

  behaviors:

    # github.behaviors.deployHooks controls whether Sherlock
    # should act upon GitHub-based deploy hooks.
    deployHooks:
      enable: true

    # github.behaviors.collectUserInfo controls whether Sherlock
    # will look up and store GitHub user info
    collectUserInfo:
      enable: true

slack:
  # When slack.enable is true, Sherlock will initiate a
  # websocket connection with Slack upon boot. It will
  # acknowledge all events it receives, even if it isn't
  # configured to act on them (otherwise, Slack will
  # redeliver repeatedly).
  enable: false

  # When slack.enableMocked is true, Sherlock will act as
  # if slack.enable is true when the Slack client is
  # currently mocked. This is set to true in test_config.yaml.
  enableMocked: false

  # slack.debug enables debug logging in the Slack library.
  # Because it doesn't support leveling, the logs appear at
  # the info level.
  debug: false

  appToken: replace me with token starting with "xapp-"
  botToken: replace me with token starting with "xoxb-"

  colors:
    red: "#ef4444" # tailwind's red-500
    green: "#22c55e" # tailwind's green-500

  emoji:
    beehive: dsp-beehive
    beehiveLoading: dsp-beehive-loading
    beehiveWaiting: dsp-beehive-waiting
    succeeded: white_check_mark
    failed: x
    unknown: question
    alert: exclamation

  behaviors:

    # slack.behaviors.deployHooks controls whether Sherlock
    # should act upon Slack-based deploy hooks.
    deployHooks:
      enable: true

    # slack.behaviors.errors controls whether Sherlock should
    # notify a list of channels upon a 500 error.
    errors:
      enable: true
      statusCodes:
        # "Internal Server Error", sometimes used explicitly
        # but mainly Sherlock's default for when it appears
        # that it is to blame instead of the client.
        - 500
        # "Proxy Authentication Required", used if a request
        # seems not to have been processed by IAP. We notify
        # on it because it is highly unexpected and would
        # indicate a misconfiguration.
        - 407
      channels:
        - "#ap-k8s-monitor"

    reactToMentionsWithEmoji:
      enable: true
      emoji: dsp-beehive

    # slack.behaviors.collectUserInfo controls whether Sherlock
    # should look up and store Slack user info.
    collectUserInfo:
      enable: true
      restrictToEmailDomains:
        - "broadinstitute.org"

pactbroker:
  # This URL is used both to contact the broker at runtime and for Sherlock's own testing.
  url: https://pact-broker.dsp-eng-tools.broadinstitute.org
  # This auth is only used to contact the broker at runtime. Test-time authentication should be done
  # with the Pact library's standard `PACT_BROKER_USERNAME`, `PACT_BROKER_PASSWORD`, and/or
  # `PACT_BROKER_TOKEN` environment variables.
  auth:
    username: replace-username
    password: replace-password
  # Whether to enable contacting the broker at runtime. Has no impact on Sherlock's own testing.
  enable: false

argoWorkflows:
  url: https://workflows.dsp-devops.broadinstitute.org

argoCd:
  url: https://ap-argocd.dsp-devops.broadinstitute.org
  chartReleaseUrlFormatString: https://ap-argocd.dsp-devops.broadinstitute.org/applications/ap-argocd/%s
  # Note the double %% in the string, escaping the % that appears naturally in the URL (for %253D, the URL-encoded version of =).
  environmentUrlFormatString: https://ap-argocd.dsp-devops.broadinstitute.org/applications?showFavorites=false&proj=&sync=&health=&namespace=&cluster=&labels=env%%253D%s

model:
  environments:
    templates:
      # Uses appVersionResolver = "none", chartVersionResolver = "latest", and helmfileRef = "HEAD"
      autoPopulateCharts:
        - name: honeycomb
  ciRuns:
    # A list of partial CiRuns where if any has a match on all non-zero fields with an actual CiRun,
    # the actual CiRun should be considered a deploy (and should dispatch deploy hooks upon completion).
    # The schema here is defined from models.CiRun (the database type) instead of the API type.
    deployMatchers:
      - platform: github-actions
        githubActionsOwner: broadinstitute
        githubActionsRepo: terra-github-workflows
        githubActionsWorkflowPath: .github/workflows/sync-release.yaml
      - platform: github-actions
        githubActionsOwner: broadinstitute
        githubActionsRepo: terra-github-workflows
        githubActionsWorkflowPath: .github/workflows/sync-environment.yaml

beehive:
    chartReleaseUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/chart-release/%s
    environmentUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/environment/%s
    pagerdutyIntegrationUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/pagerduty-integration/%s
    reviewChangesetsUrl: https://beehive.dsp-devops.broadinstitute.org/review-changesets
