# Note that this file and any TEST_SHERLOCK_ environment variables are overlaid on top of all Sherlock config,
# including default_config.yaml. In other words, that config is still present, it can just be overridden here.

mode: debug

origins:
  - http://localhost:8080

log:
  level: warn

db:
  driver: pgx
  host: localhost
  user: sherlock
  password: password
  name: sherlock
  port: 5431
  ssl: disable
  init: true

auth:
  # These are for testing our handling of this config; tests run fully off-line
  extraPermissions:
    - email: has-extra-permissions-suitable@example.com
      suitable: true
    - email: has-extra-permissions-non-suitable@example.com
      suitable: false

hooks:
  asynchronous: false

pagerduty:
  enable: false

github:
  enableMocked: true

slack:
  enableMocked: true
  behaviors:
    errors:
      channels:
        - "#error-channel"
        - "#notification-channel"
    permissionChanges:
      channels:
        - "#notification-channel"
        - "#permission-change-channel"

pactbroker:
  enable: false

model:
  environments:
    templates:
      autoPopulateCharts:
        - name: honeycomb

self:
  overrideEmail: sherlock-test@broadinstitute.org
  overrideSubjectID: sherlock-test

rolePropagation:
  asynchronous: false
  propagators:
    devFirecloudGroupTestDisabled:
      enable: false
      workspaceDomain: test.firecloud.org

    devFirecloudGroupTestDefault:
      enable: true
      workspaceDomain: test.firecloud.org

    devFirecloudGroupTestConfig:
      enable: true
      workspaceDomain: test.firecloud.org
      timeout: 10s
      userEmailDomainsToReplace:
        - broadinstitute.org
      toleratedUsers:
        - email: tolerated@test.firecloud.org
