/*
Sherlock

The Data Science Platform's source-of-truth service

API version: development
Contact: dsp-devops@broadinstitute.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sherlock

import (
	"encoding/json"
)

// V2controllersCreatableChartDeployRecord struct for V2controllersCreatableChartDeployRecord
type V2controllersCreatableChartDeployRecord struct {
	// Required when creating
	ChartRelease *string `json:"chartRelease,omitempty"`
	// When creating, will default to the value currently held by the chart release
	ExactAppVersion *string `json:"exactAppVersion,omitempty"`
	// When creating, will default to the value currently held by the chart release
	ExactChartVersion *string `json:"exactChartVersion,omitempty"`
	// When creating, will default to the value currently held by the chart release
	HelmfileRef *string `json:"helmfileRef,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V2controllersCreatableChartDeployRecord V2controllersCreatableChartDeployRecord

// NewV2controllersCreatableChartDeployRecord instantiates a new V2controllersCreatableChartDeployRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2controllersCreatableChartDeployRecord() *V2controllersCreatableChartDeployRecord {
	this := V2controllersCreatableChartDeployRecord{}
	return &this
}

// NewV2controllersCreatableChartDeployRecordWithDefaults instantiates a new V2controllersCreatableChartDeployRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2controllersCreatableChartDeployRecordWithDefaults() *V2controllersCreatableChartDeployRecord {
	this := V2controllersCreatableChartDeployRecord{}
	return &this
}

// GetChartRelease returns the ChartRelease field value if set, zero value otherwise.
func (o *V2controllersCreatableChartDeployRecord) GetChartRelease() string {
	if o == nil || o.ChartRelease == nil {
		var ret string
		return ret
	}
	return *o.ChartRelease
}

// GetChartReleaseOk returns a tuple with the ChartRelease field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2controllersCreatableChartDeployRecord) GetChartReleaseOk() (*string, bool) {
	if o == nil || o.ChartRelease == nil {
		return nil, false
	}
	return o.ChartRelease, true
}

// HasChartRelease returns a boolean if a field has been set.
func (o *V2controllersCreatableChartDeployRecord) HasChartRelease() bool {
	if o != nil && o.ChartRelease != nil {
		return true
	}

	return false
}

// SetChartRelease gets a reference to the given string and assigns it to the ChartRelease field.
func (o *V2controllersCreatableChartDeployRecord) SetChartRelease(v string) {
	o.ChartRelease = &v
}

// GetExactAppVersion returns the ExactAppVersion field value if set, zero value otherwise.
func (o *V2controllersCreatableChartDeployRecord) GetExactAppVersion() string {
	if o == nil || o.ExactAppVersion == nil {
		var ret string
		return ret
	}
	return *o.ExactAppVersion
}

// GetExactAppVersionOk returns a tuple with the ExactAppVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2controllersCreatableChartDeployRecord) GetExactAppVersionOk() (*string, bool) {
	if o == nil || o.ExactAppVersion == nil {
		return nil, false
	}
	return o.ExactAppVersion, true
}

// HasExactAppVersion returns a boolean if a field has been set.
func (o *V2controllersCreatableChartDeployRecord) HasExactAppVersion() bool {
	if o != nil && o.ExactAppVersion != nil {
		return true
	}

	return false
}

// SetExactAppVersion gets a reference to the given string and assigns it to the ExactAppVersion field.
func (o *V2controllersCreatableChartDeployRecord) SetExactAppVersion(v string) {
	o.ExactAppVersion = &v
}

// GetExactChartVersion returns the ExactChartVersion field value if set, zero value otherwise.
func (o *V2controllersCreatableChartDeployRecord) GetExactChartVersion() string {
	if o == nil || o.ExactChartVersion == nil {
		var ret string
		return ret
	}
	return *o.ExactChartVersion
}

// GetExactChartVersionOk returns a tuple with the ExactChartVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2controllersCreatableChartDeployRecord) GetExactChartVersionOk() (*string, bool) {
	if o == nil || o.ExactChartVersion == nil {
		return nil, false
	}
	return o.ExactChartVersion, true
}

// HasExactChartVersion returns a boolean if a field has been set.
func (o *V2controllersCreatableChartDeployRecord) HasExactChartVersion() bool {
	if o != nil && o.ExactChartVersion != nil {
		return true
	}

	return false
}

// SetExactChartVersion gets a reference to the given string and assigns it to the ExactChartVersion field.
func (o *V2controllersCreatableChartDeployRecord) SetExactChartVersion(v string) {
	o.ExactChartVersion = &v
}

// GetHelmfileRef returns the HelmfileRef field value if set, zero value otherwise.
func (o *V2controllersCreatableChartDeployRecord) GetHelmfileRef() string {
	if o == nil || o.HelmfileRef == nil {
		var ret string
		return ret
	}
	return *o.HelmfileRef
}

// GetHelmfileRefOk returns a tuple with the HelmfileRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2controllersCreatableChartDeployRecord) GetHelmfileRefOk() (*string, bool) {
	if o == nil || o.HelmfileRef == nil {
		return nil, false
	}
	return o.HelmfileRef, true
}

// HasHelmfileRef returns a boolean if a field has been set.
func (o *V2controllersCreatableChartDeployRecord) HasHelmfileRef() bool {
	if o != nil && o.HelmfileRef != nil {
		return true
	}

	return false
}

// SetHelmfileRef gets a reference to the given string and assigns it to the HelmfileRef field.
func (o *V2controllersCreatableChartDeployRecord) SetHelmfileRef(v string) {
	o.HelmfileRef = &v
}

func (o V2controllersCreatableChartDeployRecord) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ChartRelease != nil {
		toSerialize["chartRelease"] = o.ChartRelease
	}
	if o.ExactAppVersion != nil {
		toSerialize["exactAppVersion"] = o.ExactAppVersion
	}
	if o.ExactChartVersion != nil {
		toSerialize["exactChartVersion"] = o.ExactChartVersion
	}
	if o.HelmfileRef != nil {
		toSerialize["helmfileRef"] = o.HelmfileRef
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *V2controllersCreatableChartDeployRecord) UnmarshalJSON(bytes []byte) (err error) {
	varV2controllersCreatableChartDeployRecord := _V2controllersCreatableChartDeployRecord{}

	if err = json.Unmarshal(bytes, &varV2controllersCreatableChartDeployRecord); err == nil {
		*o = V2controllersCreatableChartDeployRecord(varV2controllersCreatableChartDeployRecord)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "chartRelease")
		delete(additionalProperties, "exactAppVersion")
		delete(additionalProperties, "exactChartVersion")
		delete(additionalProperties, "helmfileRef")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2controllersCreatableChartDeployRecord struct {
	value *V2controllersCreatableChartDeployRecord
	isSet bool
}

func (v NullableV2controllersCreatableChartDeployRecord) Get() *V2controllersCreatableChartDeployRecord {
	return v.value
}

func (v *NullableV2controllersCreatableChartDeployRecord) Set(val *V2controllersCreatableChartDeployRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableV2controllersCreatableChartDeployRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableV2controllersCreatableChartDeployRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2controllersCreatableChartDeployRecord(val *V2controllersCreatableChartDeployRecord) *NullableV2controllersCreatableChartDeployRecord {
	return &NullableV2controllersCreatableChartDeployRecord{value: val, isSet: true}
}

func (v NullableV2controllersCreatableChartDeployRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2controllersCreatableChartDeployRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


