# debug can be either 'debug' or 'release', defaults to 'release' behavior if another value is provided
mode: debug

log:
  timestamp: true
  caller: false
  level: debug

db:
  host: localhost
  user: sherlock
  name: sherlock
  port: 5432
  ssl: disable
  maxOpenConnections: 75
  init: true

  # retryConnection is helpful especially for local testing, in case the Postgres container hasn't come up yet.
  # The liveness check won't activate until a connection is established, so this is safe to ship.
  retryConnection:
    times: 10
    interval: 1s

  # configures logging behavior just for the database
  log:
    slowThreshold: 200ms
    ignoreNotFoundWarning: true
    level: warn

  # autoMigrate will have Gorm align the database schema with its understanding of model structs post-init.
  # It should not be enabled in merged code but can be useful for development, to iterate before adding
  # SQL migration files.
  autoMigrateV1: false
  autoMigrateV2: false

auth:
  updateIntervalMinutes: 15
  broadinstitute:
    domain: broadinstitute.org
  firecloud:
    domain: firecloud.org
    groups:
      fcAdmins: fc-admins@firecloud.org
      firecloudProjectOwners: firecloud-project-owners@firecloud.org
  githubActionsOIDC:
    enable: true
    issuer: https://token.actions.githubusercontent.com
    allowedOrganizations:
      - broadinstitute

  # extraPermissions can be used to grant an exact email address access to "suitable" actions inside Sherlock,
  # regardless of that email correlating to a Firecloud account. This functionality should only be used for
  # service accounts, and the justification for this functionality existing is that adding a service account
  # here is better than actually giving the service account any actual permissions inside the Firecloud org.
  extraPermissions:
    #- email: example@dsp-tools-k8s.iam.gserviceaccount.com
    #  suitable: false

metrics:
  v1:
    enable: false
  v2:
    enable: true
    updateIntervalMinutes: 5

pagerduty:
  enable: false

model:
  environments:
    templates:
      # Uses appVersionResolver = "none", chartVersionResolver = "latest", and helmfileRef = "HEAD"
      autoPopulateCharts:
        - name: honeycomb

beehive:
    chartReleaseUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/chart-release/%s
    environmentUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/environment/%s
    pagerdutyIntegrationUrlFormatString: https://beehive.dsp-devops.broadinstitute.org/r/pagerduty-integration/%s
