/* tslint:disable */
/* eslint-disable */
/**
 * Sherlock
 * The Data Science Platform\'s source-of-truth service. Note: this API will try to load and return associations in responses, so clients won\'t need to make as many requests. This behavior isn\'t recursive, though, so associations of associations are *not* fully loaded (even if it might seem that way from looking at the data types).
 *
 * The version of the OpenAPI document: development
 * Contact: dsp-devops@broadinstitute.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SherlockSlackDeployHookV3Create
 */
export interface SherlockSlackDeployHookV3Create {
    /**
     * 
     * @type {boolean}
     * @memberof SherlockSlackDeployHookV3Create
     */
    mentionPeople?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SherlockSlackDeployHookV3Create
     */
    onChartRelease?: string;
    /**
     * 
     * @type {string}
     * @memberof SherlockSlackDeployHookV3Create
     */
    onEnvironment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SherlockSlackDeployHookV3Create
     */
    onFailure?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SherlockSlackDeployHookV3Create
     */
    onSuccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SherlockSlackDeployHookV3Create
     */
    slackChannel?: string;
}

/**
 * Check if a given object implements the SherlockSlackDeployHookV3Create interface.
 */
export function instanceOfSherlockSlackDeployHookV3Create(value: object): value is SherlockSlackDeployHookV3Create {
    return true;
}

export function SherlockSlackDeployHookV3CreateFromJSON(json: any): SherlockSlackDeployHookV3Create {
    return SherlockSlackDeployHookV3CreateFromJSONTyped(json, false);
}

export function SherlockSlackDeployHookV3CreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SherlockSlackDeployHookV3Create {
    if (json == null) {
        return json;
    }
    return {
        
        'mentionPeople': json['mentionPeople'] == null ? undefined : json['mentionPeople'],
        'onChartRelease': json['onChartRelease'] == null ? undefined : json['onChartRelease'],
        'onEnvironment': json['onEnvironment'] == null ? undefined : json['onEnvironment'],
        'onFailure': json['onFailure'] == null ? undefined : json['onFailure'],
        'onSuccess': json['onSuccess'] == null ? undefined : json['onSuccess'],
        'slackChannel': json['slackChannel'] == null ? undefined : json['slackChannel'],
    };
}

export function SherlockSlackDeployHookV3CreateToJSON(json: any): SherlockSlackDeployHookV3Create {
    return SherlockSlackDeployHookV3CreateToJSONTyped(json, false);
}

export function SherlockSlackDeployHookV3CreateToJSONTyped(value?: SherlockSlackDeployHookV3Create | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mentionPeople': value['mentionPeople'],
        'onChartRelease': value['onChartRelease'],
        'onEnvironment': value['onEnvironment'],
        'onFailure': value['onFailure'],
        'onSuccess': value['onSuccess'],
        'slackChannel': value['slackChannel'],
    };
}

