/* tslint:disable */
/* eslint-disable */
/**
 * Sherlock
 * The Data Science Platform\'s source-of-truth service. Note: this API will try to load and return associations in responses, so clients won\'t need to make as many requests. This behavior isn\'t recursive, though, so associations of associations are *not* fully loaded (even if it might seem that way from looking at the data types).
 *
 * The version of the OpenAPI document: development
 * Contact: dsp-devops@broadinstitute.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SherlockChartVersionV3Edit
 */
export interface SherlockChartVersionV3Edit {
    /**
     * Generally the Git commit message
     * @type {string}
     * @memberof SherlockChartVersionV3Edit
     */
    description?: string;
}

/**
 * Check if a given object implements the SherlockChartVersionV3Edit interface.
 */
export function instanceOfSherlockChartVersionV3Edit(value: object): boolean {
    return true;
}

export function SherlockChartVersionV3EditFromJSON(json: any): SherlockChartVersionV3Edit {
    return SherlockChartVersionV3EditFromJSONTyped(json, false);
}

export function SherlockChartVersionV3EditFromJSONTyped(json: any, ignoreDiscriminator: boolean): SherlockChartVersionV3Edit {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function SherlockChartVersionV3EditToJSON(value?: SherlockChartVersionV3Edit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value['description'],
    };
}

