/* tslint:disable */
/* eslint-disable */
/**
 * Sherlock
 * The Data Science Platform\'s source-of-truth service. Note: this API will try to load and return associations in responses, so clients won\'t need to make as many requests. This behavior isn\'t recursive, though, so associations of associations are *not* fully loaded (even if it might seem that way from looking at the data types).
 *
 * The version of the OpenAPI document: development
 * Contact: dsp-devops@broadinstitute.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SherlockIncidentV3Create
 */
export interface SherlockIncidentV3Create {
    /**
     * 
     * @type {string}
     * @memberof SherlockIncidentV3Create
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SherlockIncidentV3Create
     */
    remediatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SherlockIncidentV3Create
     */
    reviewCompletedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SherlockIncidentV3Create
     */
    startedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SherlockIncidentV3Create
     */
    ticket?: string;
}

/**
 * Check if a given object implements the SherlockIncidentV3Create interface.
 */
export function instanceOfSherlockIncidentV3Create(value: object): value is SherlockIncidentV3Create {
    return true;
}

export function SherlockIncidentV3CreateFromJSON(json: any): SherlockIncidentV3Create {
    return SherlockIncidentV3CreateFromJSONTyped(json, false);
}

export function SherlockIncidentV3CreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SherlockIncidentV3Create {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'remediatedAt': json['remediatedAt'] == null ? undefined : json['remediatedAt'],
        'reviewCompletedAt': json['reviewCompletedAt'] == null ? undefined : json['reviewCompletedAt'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'ticket': json['ticket'] == null ? undefined : json['ticket'],
    };
}

export function SherlockIncidentV3CreateToJSON(value?: SherlockIncidentV3Create | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'remediatedAt': value['remediatedAt'],
        'reviewCompletedAt': value['reviewCompletedAt'],
        'startedAt': value['startedAt'],
        'ticket': value['ticket'],
    };
}

