// Code generated by go-swagger; DO NOT EDIT.

package pagerduty_integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/broadinstitute/sherlock/sherlock-go-client/client/models"
)

// PatchAPIV2PagerdutyIntegrationsSelectorReader is a Reader for the PatchAPIV2PagerdutyIntegrationsSelector structure.
type PatchAPIV2PagerdutyIntegrationsSelectorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPIV2PagerdutyIntegrationsSelectorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPIV2PagerdutyIntegrationsSelectorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchAPIV2PagerdutyIntegrationsSelectorBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPatchAPIV2PagerdutyIntegrationsSelectorForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchAPIV2PagerdutyIntegrationsSelectorNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 407:
		result := NewPatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPatchAPIV2PagerdutyIntegrationsSelectorConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchAPIV2PagerdutyIntegrationsSelectorInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchAPIV2PagerdutyIntegrationsSelectorOK creates a PatchAPIV2PagerdutyIntegrationsSelectorOK with default headers values
func NewPatchAPIV2PagerdutyIntegrationsSelectorOK() *PatchAPIV2PagerdutyIntegrationsSelectorOK {
	return &PatchAPIV2PagerdutyIntegrationsSelectorOK{}
}

/* PatchAPIV2PagerdutyIntegrationsSelectorOK describes a response with status code 200, with default header values.

OK
*/
type PatchAPIV2PagerdutyIntegrationsSelectorOK struct {
	Payload *models.V2controllersPagerdutyIntegration
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/pagerduty-integrations/{selector}][%d] patchApiV2PagerdutyIntegrationsSelectorOK  %+v", 200, o.Payload)
}
func (o *PatchAPIV2PagerdutyIntegrationsSelectorOK) GetPayload() *models.V2controllersPagerdutyIntegration {
	return o.Payload
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V2controllersPagerdutyIntegration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIV2PagerdutyIntegrationsSelectorBadRequest creates a PatchAPIV2PagerdutyIntegrationsSelectorBadRequest with default headers values
func NewPatchAPIV2PagerdutyIntegrationsSelectorBadRequest() *PatchAPIV2PagerdutyIntegrationsSelectorBadRequest {
	return &PatchAPIV2PagerdutyIntegrationsSelectorBadRequest{}
}

/* PatchAPIV2PagerdutyIntegrationsSelectorBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PatchAPIV2PagerdutyIntegrationsSelectorBadRequest struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/pagerduty-integrations/{selector}][%d] patchApiV2PagerdutyIntegrationsSelectorBadRequest  %+v", 400, o.Payload)
}
func (o *PatchAPIV2PagerdutyIntegrationsSelectorBadRequest) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIV2PagerdutyIntegrationsSelectorForbidden creates a PatchAPIV2PagerdutyIntegrationsSelectorForbidden with default headers values
func NewPatchAPIV2PagerdutyIntegrationsSelectorForbidden() *PatchAPIV2PagerdutyIntegrationsSelectorForbidden {
	return &PatchAPIV2PagerdutyIntegrationsSelectorForbidden{}
}

/* PatchAPIV2PagerdutyIntegrationsSelectorForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PatchAPIV2PagerdutyIntegrationsSelectorForbidden struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorForbidden) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/pagerduty-integrations/{selector}][%d] patchApiV2PagerdutyIntegrationsSelectorForbidden  %+v", 403, o.Payload)
}
func (o *PatchAPIV2PagerdutyIntegrationsSelectorForbidden) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIV2PagerdutyIntegrationsSelectorNotFound creates a PatchAPIV2PagerdutyIntegrationsSelectorNotFound with default headers values
func NewPatchAPIV2PagerdutyIntegrationsSelectorNotFound() *PatchAPIV2PagerdutyIntegrationsSelectorNotFound {
	return &PatchAPIV2PagerdutyIntegrationsSelectorNotFound{}
}

/* PatchAPIV2PagerdutyIntegrationsSelectorNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PatchAPIV2PagerdutyIntegrationsSelectorNotFound struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorNotFound) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/pagerduty-integrations/{selector}][%d] patchApiV2PagerdutyIntegrationsSelectorNotFound  %+v", 404, o.Payload)
}
func (o *PatchAPIV2PagerdutyIntegrationsSelectorNotFound) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired creates a PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired with default headers values
func NewPatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired() *PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired {
	return &PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired{}
}

/* PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired describes a response with status code 407, with default header values.

Proxy Authentication Required
*/
type PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/pagerduty-integrations/{selector}][%d] patchApiV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired  %+v", 407, o.Payload)
}
func (o *PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorProxyAuthenticationRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIV2PagerdutyIntegrationsSelectorConflict creates a PatchAPIV2PagerdutyIntegrationsSelectorConflict with default headers values
func NewPatchAPIV2PagerdutyIntegrationsSelectorConflict() *PatchAPIV2PagerdutyIntegrationsSelectorConflict {
	return &PatchAPIV2PagerdutyIntegrationsSelectorConflict{}
}

/* PatchAPIV2PagerdutyIntegrationsSelectorConflict describes a response with status code 409, with default header values.

Conflict
*/
type PatchAPIV2PagerdutyIntegrationsSelectorConflict struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorConflict) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/pagerduty-integrations/{selector}][%d] patchApiV2PagerdutyIntegrationsSelectorConflict  %+v", 409, o.Payload)
}
func (o *PatchAPIV2PagerdutyIntegrationsSelectorConflict) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchAPIV2PagerdutyIntegrationsSelectorInternalServerError creates a PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError with default headers values
func NewPatchAPIV2PagerdutyIntegrationsSelectorInternalServerError() *PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError {
	return &PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError{}
}

/* PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError struct {
	Payload *models.ErrorsErrorResponse
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /api/v2/pagerduty-integrations/{selector}][%d] patchApiV2PagerdutyIntegrationsSelectorInternalServerError  %+v", 500, o.Payload)
}
func (o *PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError) GetPayload() *models.ErrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV2PagerdutyIntegrationsSelectorInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
