# debug can be either 'debug' or 'release', defaults to 'release' behavior if another value is provided
mode: debug

log:
  timestamp: true
  caller: false
  level: debug

db:
  host: localhost
  user: sherlock
  name: sherlock
  port: 5432
  ssl: disable
  init: true

  # autoMigrate will have Gorm align the database schema with its understanding of model structs post-init.
  # It should not be enabled in merged code but can be useful for development, to iterate before adding
  # SQL migration files.
  autoMigrateV1: false
  autoMigrateV2: false

auth:
  updateIntervalMinutes: 15
  broadinstitute:
    domain: broadinstitute.org
  firecloud:
    domain: firecloud.org
    groups:
      fcAdmins: fc-admins@firecloud.org
      firecloudProjectOwners: firecloud-project-owners@firecloud.org
