# Note that this file and any TEST_SHERLOCK_ environment variables are overlaid on top of all Sherlock config,
# including default_config.yaml. In other words, that config is still present, it can just be overridden here.

mode: debug

log:
  level: warn

db:
  host: localhost
  user: sherlock
  password: password
  name: sherlock
  port: 5432
  ssl: disable
  init: true
