name: Get Environment

on:
  workflow_call:

    inputs:

      ##
      ## Required configuration:
      ##

      environment-name:
        required: true
        type: string
        description: "The name of the environment to get"

      ##
      ## Sherlock configuration:
      ##

      use-sherlock-dev:
        required: false
        type: boolean
        default: false
        description: "If the environment should be gotten from the DevOps-use development Sherlock instance instead of the general-use production instance"

    outputs:
      lifecycle:
        description: "The lifecycle of the environment"
        value: ${{ jobs.get.outputs.lifecycle }}
      owner:
        description: "The owner of the environment"
        value: ${{ jobs.get.outputs.owner }}

env:
  SHERLOCK_PROD_URL: 'https://sherlock.dsp-devops.broadinstitute.org'
  SHERLOCK_DEV_URL: 'https://sherlock-dev.dsp-devops.broadinstitute.org'
  BEEHIVE_PROD_URL: 'https://beehive.dsp-devops.broadinsitute.org'
  BEEHIVE_DEV_URL: 'https://beehive-dev.dsp-devops.broadinstitute.org'
  BEEHIVE_PROD_VANITY_URL: 'https://broad.io/beehive'
  BEEHIVE_DEV_VANITY_URL: 'https://broad.io/beehive-dev'

jobs:
  get:
    runs-on: ubuntu-22.04
    permissions:
      id-token: 'write'
    outputs:
      lifecycle: ${{ steps.parse.outputs.lifecycle }}
      owner: ${{ steps.parse.outputs.owner }}
    steps:
      - name: "Authenticate to GCP"
        id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'dsp-tools-iap-access@dsp-tools-k8s.iam.gserviceaccount.com'
          token_format: 'id_token'
          id_token_audience: '1038484894585-k8qvf7l876733laev0lm8kenfa2lj6bn.apps.googleusercontent.com'
          id_token_include_email: true
          create_credentials_file: false
          export_environment_variables: false

      - name: "Get from Sherlock Dev"
        if: ${{ inputs.use-sherlock-dev == true }}
        shell: bash
        run: |
          set -ex
          curl --fail-with-body \
            "$SHERLOCK_DEV_URL/api/v2/environments/${{ inputs.environment-name }}" \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ steps.auth.outputs.id_token }}' \
            -o "$RUNNER_TEMP/response.json"

      - name: "Get from Sherlock Prod"
        if: ${{ inputs.use-sherlock-dev == false }}
        shell: bash
        run: |
          set -ex
          curl --fail-with-body \
            "$SHERLOCK_PROD_URL/api/v2/environments/${{ inputs.environment-name }}" \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ steps.auth.outputs.id_token }}' \
            -o "$RUNNER_TEMP/response.json"
      
      - name: "Parse Outputs"
        id: 'parse'
        shell: bash
        run: |
          jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' $RUNNER_TEMP/response.json >> $GITHUB_OUTPUT
