name: generate-swagger-spec-and-client-libs
on:
  pull_request:
    branches:
      - main
    types:
      - closed
concurrency: commits-to-mainline

env:
  GO_SWAGGER_VERSION: v0.29.0

jobs:
  gen-swagger:
    name: generate-swagger-spec-and-client-libs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Install swaggo
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate swagger spec
        run: make generate-swagger
      - name: Generate Go Client Lib
        # Running this tool via docker because go-swagger's local install procedures are a huge pain to perform from within a github action
        run: |
          docker run --rm -e GOPATH=/go \
            -v $(go env GOPATH):/go \
            -v $HOME:$HOME -w "$(pwd)" \
            quay.io/goswagger/swagger:${GO_SWAGGER_VERSION} \
            generate client -f docs/swagger.json -A sherlock --default-scheme=https -m clients/go/client/models -c clients/go/client
      - name: Generate Typescript Client Lib
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/docs/swagger.json \
            -g typescript-fetch \
            -o /local/clients/typescript-fetch \
            --additional-properties=disallowAdditionalPropertiesIfNotPresent=false \
            --additional-properties=supportsES6=true \
            --additional-properties=npmName=sherlock-client \
            --additional-properties=npmVersion=$(git tag --points-at HEAD)
      - name: Generate Go (openapi-generator) Client Lib
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/docs/swagger.json \
            -g go \
            -o /local/clients/go-openapi-generator \
            --additional-properties=disallowAdditionalPropertiesIfNotPresent=false \
            --additional-properties=packageName=sherlockclient \
            --additional-properties=packageVersion=$(git tag --points-at HEAD)
      - name: Set up Git
        shell: bash
        run: |
          git config --global user.name 'broadbot'
          git config --global user.email 'broadbot@broadinstitute.org'
      - name: Add and commit swagger spec
        shell: bash
        run: |
          git add .
          git commit --allow-empty --message "[gen-swagger-and-clients] update swagger spec"
      - name: Push to main with retry
        uses: ./.github/actions/push-with-retry
