name: generate-swagger-spec-and-client-libs
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - 'README.md'
concurrency: commits-to-mainline

env:
  GO_SWAGGER_VERSION: v0.29.0

jobs:
  gen-swagger:
    name: generate-swagger-spec-and-client-libs
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Auth to GCP
        id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'dsp-artifact-registry-push@dsp-artifact-registry.iam.gserviceaccount.com'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Install swaggo
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate swagger spec
        run: make generate-swagger


      - name: Generate Go Client Lib
        # Running this tool via docker because go-swagger's local install procedures are a huge pain to perform from within a github action
        run: |
          docker run --rm -e GOPATH=/go \
            -v $(go env GOPATH):/go \
            -v $HOME:$HOME -w "$(pwd)" \
            quay.io/goswagger/swagger:${GO_SWAGGER_VERSION} \
            generate client -f docs/swagger.json -A sherlock --default-scheme=https -m clients/go/client/models -c clients/go/client
          

      - name: Generate Typescript (swagger-codegen) Client Lib
        run: |
          docker run --rm -v "${PWD}:/local" swaggerapi/swagger-codegen-cli generate \
            -i /local/docs/swagger.json \
            -l typescript-fetch \
            -o /local/clients/typescript \
            --additional-properties=supportsES6=true,npmName=@sherlock-js-client/sherlock,npmVersion=$(git tag --points-at HEAD)
      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install and build
        working-directory: clients/typescript
        run: |
          npm install --save-dev
          npm install --save-dev @types/jest
          npm run build
      - name: Authenticate and publish
        working-directory: clients/typescript
        run: |
          npx google-artifactregistry-auth --yes
          npm publish

      - name: Set up Git
        shell: bash
        run: |
          git config --global user.name 'broadbot'
          git config --global user.email 'broadbot@broadinstitute.org'
      - name: Add and commit swagger spec
        shell: bash
        run: |
          git add .
          git commit --allow-empty --message "[gen-swagger-and-clients] update swagger spec"
      - name: Push to main with retry
        uses: ./.github/actions/push-with-retry
