name: Run Unit and Functional Tests
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  # This job will only run unit tests and coverage report is generated based on them.
  # Functional tests are handled in a separate job
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: run all tests
      run: make tests-with-coverage
      env:
        SHERLOCK_DB_INIT: "true"
        SHERLOCK_DB_PASSWORD: "password"
        SHERLOCK_DB_HOST: "localhost"
    - name: upload unit test coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./cover.out
