name: Lint Sherlock
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sherlock-lint.yaml"
      - "sherlock/**"
      - "!sherlock/docs/**"
      - "go-shared/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/sherlock-lint.yaml"
      - "sherlock/**"
      - "!sherlock/docs/**"
      - "go-shared/**"
jobs:
  golangci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["sherlock", "go-shared", "sherlock-webhook-proxy"]
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: golangci-lint command line arguments.
          args: --timeout 4m0s

          # Optional: working directory, useful for monorepos
          working-directory: ${{ matrix.directory }}

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
