name: Test Sherlock
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "sherlock/go.mod"
    - name: Install pact-go
      run: make install-pact
    - name: Run tests
      run: make test-with-coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        files: go-shared/cover.out,sherlock/cover.out
        token: ${{ secrets.CODECOV_TOKEN }}
