name: Re-Run Checks on Review
on:
  pull_request_review:
    types:
      - edited
      - dismissed
      - submitted
    branches:
      - main

jobs:
  rerun-checks:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Rerun Checks
        uses: shqear93/rerun-checks@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          check-names: 'check-reviews'
