name: Run Unit and Integration Tests
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  # This job will only run unit tests and coverage report is generated based on them.
  # Integration tests are handled in a separate job
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        # Not real db credentials, only used for ephemeral integration test runs
        env:
          POSTGRES_USER: sherlock
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 5432:5432
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: run all tests
      run: go test -v -coverprofile=cover.out -covermode=count ./...
      env:
        SHERLOCK_DBINIT: "true"
        SHERLOCK_DBPASSWORD: "password"
        SHERLOCK_DBHOST: "localhost"
    - name: upload unit test coverage report
      uses: codecov/codecov-action@v1
      with:
        files: ./cover.out
