on:
  workflow_dispatch:

env:
  SHERLOCK_PROD_URL: 'https://sherlock.dsp-devops.broadinstitute.org'
  SHERLOCK_DEV_URL: 'https://sherlock-dev.dsp-devops.broadinstitute.org'
  BEEHIVE_PROD_URL: 'https://beehive.dsp-devops.broadinsitute.org'
  BEEHIVE_DEV_URL: 'https://beehive-dev.dsp-devops.broadinstitute.org'
  BEEHIVE_PROD_VANITY_URL: 'https://broad.io/beehive'
  BEEHIVE_DEV_VANITY_URL: 'https://broad.io/beehive-dev'

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: "Authenticate to GCP"
        id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'dsp-tools-iap-access@dsp-tools-k8s.iam.gserviceaccount.com'
          token_format: 'id_token'
          id_token_audience: '1038484894585-k8qvf7l876733laev0lm8kenfa2lj6bn.apps.googleusercontent.com'
          id_token_include_email: true
          create_credentials_file: false
          export_environment_variables: false
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)

      - name: Try to request from Sherlock
        shell: bash
        run: |
          set -ex
          echo '```' >> $GITHUB_STEP_SUMMARY
          curl --fail-with-body \
            "$SHERLOCK_DEV_URL/my-user" \
            -H 'Content-Type: application/json' \
            -H 'X-GHA-OIDC-JWT: ${{ steps.idtoken.outputs.id_token }}' \
            -H 'Authorization: Bearer ${{ steps.auth.outputs.id_token }}' | jq >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY