name: Run Unit Tests
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  # This job will only run unit tests and coverage report is generated based on them.
  # Integration tests are handled in a separate job
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: run unit tests
      run: go test -v -short -coverprofile=cover.out -covermode=count ./...
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1
      with:
        files: ./cover.out
        flags: unittests
