// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SherlockGithubActionsDeployHookV3 sherlock github actions deploy hook v3
//
// swagger:model sherlock.GithubActionsDeployHookV3
type SherlockGithubActionsDeployHookV3 struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"createdAt,omitempty"`

	// github actions default ref
	GithubActionsDefaultRef string `json:"githubActionsDefaultRef,omitempty"`

	// github actions owner
	GithubActionsOwner string `json:"githubActionsOwner,omitempty"`

	// This field determines what git ref the workflow will be run on. The default of always-use-default-ref always uses the default ref; use-app-version-as-ref will use the app version (when available) as the ref, useful when versions are always commit hashes or tags; use-app-version-commit-as-ref will use the app version's commit (when available) as the ref, useful when the repo is configured to fully report app versions to Sherlock.
	// Enum: [always-use-default-ref use-app-version-as-ref use-app-version-commit-as-ref]
	GithubActionsRefBehavior *string `json:"githubActionsRefBehavior,omitempty"`

	// github actions repo
	GithubActionsRepo string `json:"githubActionsRepo,omitempty"`

	// These workflow inputs will be passed statically as-is to GitHub's workflow dispatch API (https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event) as the `inputs` parameter object.
	GithubActionsWorkflowInputs interface{} `json:"githubActionsWorkflowInputs,omitempty"`

	// github actions workflow path
	GithubActionsWorkflowPath string `json:"githubActionsWorkflowPath,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// on chart release
	OnChartRelease string `json:"onChartRelease,omitempty"`

	// on environment
	OnEnvironment string `json:"onEnvironment,omitempty"`

	// on failure
	OnFailure bool `json:"onFailure,omitempty"`

	// on success
	OnSuccess bool `json:"onSuccess,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updatedAt,omitempty"`
}

// Validate validates this sherlock github actions deploy hook v3
func (m *SherlockGithubActionsDeployHookV3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGithubActionsRefBehavior(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SherlockGithubActionsDeployHookV3) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("createdAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var sherlockGithubActionsDeployHookV3TypeGithubActionsRefBehaviorPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["always-use-default-ref","use-app-version-as-ref","use-app-version-commit-as-ref"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sherlockGithubActionsDeployHookV3TypeGithubActionsRefBehaviorPropEnum = append(sherlockGithubActionsDeployHookV3TypeGithubActionsRefBehaviorPropEnum, v)
	}
}

const (

	// SherlockGithubActionsDeployHookV3GithubActionsRefBehaviorAlwaysDashUseDashDefaultDashRef captures enum value "always-use-default-ref"
	SherlockGithubActionsDeployHookV3GithubActionsRefBehaviorAlwaysDashUseDashDefaultDashRef string = "always-use-default-ref"

	// SherlockGithubActionsDeployHookV3GithubActionsRefBehaviorUseDashAppDashVersionDashAsDashRef captures enum value "use-app-version-as-ref"
	SherlockGithubActionsDeployHookV3GithubActionsRefBehaviorUseDashAppDashVersionDashAsDashRef string = "use-app-version-as-ref"

	// SherlockGithubActionsDeployHookV3GithubActionsRefBehaviorUseDashAppDashVersionDashCommitDashAsDashRef captures enum value "use-app-version-commit-as-ref"
	SherlockGithubActionsDeployHookV3GithubActionsRefBehaviorUseDashAppDashVersionDashCommitDashAsDashRef string = "use-app-version-commit-as-ref"
)

// prop value enum
func (m *SherlockGithubActionsDeployHookV3) validateGithubActionsRefBehaviorEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, sherlockGithubActionsDeployHookV3TypeGithubActionsRefBehaviorPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SherlockGithubActionsDeployHookV3) validateGithubActionsRefBehavior(formats strfmt.Registry) error {
	if swag.IsZero(m.GithubActionsRefBehavior) { // not required
		return nil
	}

	// value enum
	if err := m.validateGithubActionsRefBehaviorEnum("githubActionsRefBehavior", "body", *m.GithubActionsRefBehavior); err != nil {
		return err
	}

	return nil
}

func (m *SherlockGithubActionsDeployHookV3) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updatedAt", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sherlock github actions deploy hook v3 based on context it is used
func (m *SherlockGithubActionsDeployHookV3) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SherlockGithubActionsDeployHookV3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SherlockGithubActionsDeployHookV3) UnmarshalBinary(b []byte) error {
	var res SherlockGithubActionsDeployHookV3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
